<a href="https://colab.research.google.com/github/RenanCOliveira93/RenanCOliveira93/blob/main/cunha_projetoIND.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## INSTALAÇÃO DE BIBLIOTECAS E IMPORTAÇÃO DE MÓDULOS E FUNÇÕES

Todas as importações que forem utilizadas serão feitas neste bloco.

In [ ]:
!pip install pyspark
!pip install pandera
!pip install gcsfs

In [ ]:
!pip install -q gcsfs

In [ ]:
import pandas as pd
import pandera as pa
import pyspark

from pyspark.sql import SparkSession
from pyspark import SparkConf
import pyspark.sql.functions as F

from google.cloud import storage
import os

In [ ]:
from google.cloud import client

In [ ]:
from pyspark.sql.types import *

In [ ]:
from pyspark import sql

In [ ]:
from pyspark.sql.window import Window
from pyspark.sql.functions import rank
from pyspark.sql.functions import col,avg,sum,min,max,row_number

In [ ]:
import numpy as py

In [ ]:
# INSTALAÇÃO DO MONGODB

!pip install pymongo[srv]

Requirement already satisfied: pymongo[srv] in /usr/local/lib/python3.7/dist-packages (4.0.2)
Collecting dnspython<3.0.0,>=1.16.0
  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
     |████████████████████████████████| 269 kB 5.1 MB/s
Installing collected packages: dnspython
Successfully installed dnspython-2.2.1

In [ ]:
from pyspark.sql.functions import row_number

In [ ]:
# IMPORTAÇÃO DAS FUNÇÕES

import pymongo
from pymongo import MongoClient

## CONEXÕES EXTERNAS (MONGO E GCP)

In [ ]:
# CONEXÃO COM MINHA CHAVE NA MINHA BUCKET
serviceAccountKEY = '/content/root-slate-339219-7c6129f0eb9a.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccountKEY

In [ ]:
cliente = storage.Client()
bucket = cliente.get_bucket('cunha_projeto_individual')

In [ ]:
# LIGAÇÃO PARA PEGAR MEU ARQUIVO NO GCP, MAIS A FRENTE ESTE 'PATH' SERÁ 
# TRANSFORMADO EM DATAFRAME


path = 'gs://cunha_projeto_individual/marketing_campaign.csv'

In [ ]:
#CONEXÃO COM O CLUSTER NO MONGO

client = pymongo.MongoClient("mongodb+srv://RenanOliveira93:Rg496652850@aulademongo.5xejl.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")

In [ ]:
#ACESSAR MEU CLUSTER E CRIAR NOVA COLEÇÃO

db = client["aulamongo"]
colecao = db.originalProjeto

In [ ]:
colecao.count_documents({})

2240

Antes de prosseguir, vamos rodar o primeiro codigo do pandas para gerar o dataframe original.

In [ ]:
df_pandas = pd.read_csv(path, sep=',')

In [ ]:
df_pandas.fillna(0)

In [ ]:
# AGORA VOU CRIAR O DF E INSERIR NA COLEÇÃO, MUITA ATENÇÃO A RODAR ESSE CODIGO VARIAS VEZES
'''
original = df_pandas.to_dict("records")

colecao.insert_many(original)
'''

'\noriginal = df_pandas.to_dict("records")\n\ncolecao.insert_many(original)\n'

In [ ]:
extrator = colecao.find({})
mongo_df = pd.DataFrame(list(extrator))

In [ ]:
mongo_df

,_id,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,6235390f45229dadf8be3340,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,...,7,0,0,0,0,0,0,3,11,1
1,6235390f45229dadf8be3341,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,...,5,0,0,0,0,0,0,3,11,0
2,6235390f45229dadf8be3342,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,...,4,0,0,0,0,0,0,3,11,0
3,6235390f45229dadf8be3343,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,...,6,0,0,0,0,0,0,3,11,0
4,6235390f45229dadf8be3344,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,6235390f45229dadf8be3bfb,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,...,5,0,0,0,0,0,0,3,11,0
2236,6235390f45229dadf8be3bfc,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,...,7,0,0,0,1,0,0,3,11,0
2237,6235390f45229dadf8be3bfd,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,...,6,0,1,0,0,0,0,3,11,0
2238,6235390f45229dadf8be3bfe,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,...,3,0,0,0,0,0,0,3,11,0
2239,6235390f45229dadf8be3bff,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,...,7,0,0,0,0,0,0,3,11,1

## PANDAS

In [ ]:
# INICIALMENTE ESTOU CONFIRMANDO SE O PANDAS ESTÁ RECONHECENDO O ARQUIVO VINDO DO GCP ATRAVÉS DA VARIAVEL "PATH"

# df_pandas = pd.read_csv(path, sep=',') comando ja utilizado acima para importar o MongoDB
df_pandas

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [ ]:
#AQUI VOU CRIAR UM SEGUNDO DATAFRAME PRA TER O PRIMEIRO COMO BACKUP.

df2 = df_pandas.copy()

In [ ]:
# VERIFICAR O TIPO DE CADA COLUNA ANTES DE MEXER  NELA

df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [ ]:
# CONSULTA DE DADOS NULOS
df2.isna().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [ ]:
# COMO NÃO OPTEI POR BIBLIOTECA DE TRADUÇÃO, ENTÃO TRADUZIREI INDIVIDUALMENTE.
# TRADUÇÃO DO NOME DE CADA COLUNA

df2.rename(columns={
    'ID':'identificacao',
    'Year_Birth':'ano_nascimento',
    'Education':'escolaridade',
    'Marital_Status':'estado_civil',
    'Income':'renda_anual',
    'Kidhome':'num_criancas_casa',
    'Teenhome':'num_adolescentes_casa',
    'Dt_Customer':'cliente_desde',
    'Recency':'dias_ultima_compra',
    'MntWines':'gasto_com_vinho_2ultimos_anos',
    'MntFruits':'gasto_com_frutas_2ultimos_anos',
    'MntMeatProducts':'gasto_com_carnes_2ultimos_anos',
    'MntFishProducts':'gasto_com_peixes_2ultimos_anos',
    'MntSweetProducts':'gasto_com_doces_2ultimos_anos',
    'MntGoldProds':'gasto_com_ouro_2ultimos_anos',
    'NumDealsPurchases':'qtd_descontos_feitos',
    'NumWebPurchases':'compras_pela_internet',
    'NumCatalogPurchases':'compras_usando_catalago',
    'NumStorePurchases':'compras_feitas_lojaFisica',
    'NumWebVisitsMonth':'visitantes_site_mensal',
    'AcceptedCmp3':'aceitou_promocao3',
    'AcceptedCmp4':'aceitou_promocao4',
    'AcceptedCmp5':'aceitou_promocao5',
    'AcceptedCmp1':'aceitou_promocao1',
    'AcceptedCmp2':'aceitou_promocao2',
    'Complain':'reclamacao_2anos',
    'Z_CostContact':'custo_cupon_desconto',
    'Z_Revenue':'receita',
    'Response':'aceitou_ultima_campanha'},inplace=True)

In [ ]:
# VOU TRADUZIR O CONTEUDO DA COLUNA, POR PRECAUÇÃO VOU CRIAR UM BACKUP DAS MESMAS.

df2['Escolaridade_bkp'] = df2.escolaridade
df2['Estado_civil_bkp']= df2.estado_civil

In [ ]:
# CONFERINDO AS PALAVRAS QUE DEVERÃO SER TRADUZIDAS EM 'escolaridade':
sorted(pd.unique(df2['escolaridade']))

['2n Cycle', 'Basic', 'Graduation', 'Master', 'PhD']

In [ ]:
# CONFERINDO AS PALAVRAS QUE DEVERÃO SER TRADUZIDAS EM 'estado_civil':
sorted(pd.unique(df2['estado_civil']))

['Absurd',
 'Alone',
 'Divorced',
 'Married',
 'Single',
 'Together',
 'Widow',
 'YOLO']

In [ ]:
# TRADUZINDO O CONTEÚDO DAS COLUNAS:

df2['escolaridade'] = df2['escolaridade'].map({'2n Cycle':'Pos-graduado', 'Basic':'Fundamental','Graduation':'Bacharel','Master':'Mestrado','PhD':'Doutorado'})

df2['estado_civil'] = df2['estado_civil'].map({'Absurd':'Assexuada', 'Alone':'Sozinho(a)','Divorced':'Divorciada(o)','Married':'Casado(a)','Single':'Solteira(o)','Together':'Uniao_Estavel','Widow':'viuvo(a)','YOLO':'Livre'})

In [ ]:
#CONFERINDO SE TUDO OCORREU CONFORME PLANEJADO:
display(df2)

,identificacao,ano_nascimento,escolaridade,estado_civil,renda_anual,num_criancas_casa,num_adolescentes_casa,cliente_desde,dias_ultima_compra,gasto_com_vinho_2ultimos_anos,...,aceitou_promocao4,aceitou_promocao5,aceitou_promocao1,aceitou_promocao2,reclamacao_2anos,custo_cupon_desconto,receita,aceitou_ultima_campanha,Escolaridade_bkp,Estado_civil_bkp
0,5524,1957,Bacharel,Solteira(o),58138.0,0,0,04-09-2012,58,635,...,0,0,0,0,0,3,11,1,Graduation,Single
1,2174,1954,Bacharel,Solteira(o),46344.0,1,1,08-03-2014,38,11,...,0,0,0,0,0,3,11,0,Graduation,Single
2,4141,1965,Bacharel,Uniao_Estavel,71613.0,0,0,21-08-2013,26,426,...,0,0,0,0,0,3,11,0,Graduation,Together
3,6182,1984,Bacharel,Uniao_Estavel,26646.0,1,0,10-02-2014,26,11,...,0,0,0,0,0,3,11,0,Graduation,Together
4,5324,1981,Doutorado,Casado(a),58293.0,1,0,19-01-2014,94,173,...,0,0,0,0,0,3,11,0,PhD,Married
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Bacharel,Casado(a),61223.0,0,1,13-06-2013,46,709,...,0,0,0,0,0,3,11,0,Graduation,Married
2236,4001,1946,Doutorado,Uniao_Estavel,64014.0,2,1,10-06-2014,56,406,...,0,0,1,0,0,3,11,0,PhD,Together
2237,7270,1981,Bacharel,Divorciada(o),56981.0,0,0,25-01-2014,91,908,...,1,0,0,0,0,3,11,0,Graduation,Divorced
2238,8235,1956,Mestrado,Uniao_Estavel,69245.0,0,1,24-01-2014,8,428,...,0,0,0,0,0,3,11,0,Master,Together
2239,9405,1954,Doutorado,Casado(a),52869.0,1,1,15-10-2012,40,84,...,0,0,0,0,0,3,11,1,PhD,Married

In [ ]:
# CONFERINDO NOVAMENTE A EXISTENCIA DE VALORES NULOS
df2.isna().sum()

identificacao                      0
ano_nascimento                     0
escolaridade                       0
estado_civil                       0
renda_anual                       24
num_criancas_casa                  0
num_adolescentes_casa              0
cliente_desde                      0
dias_ultima_compra                 0
gasto_com_vinho_2ultimos_anos      0
gasto_com_frutas_2ultimos_anos     0
gasto_com_carnes_2ultimos_anos     0
gasto_com_peixes_2ultimos_anos     0
gasto_com_doces_2ultimos_anos      0
gasto_com_ouro_2ultimos_anos       0
qtd_descontos_feitos               0
compras_pela_internet              0
compras_usando_catalago            0
compras_feitas_lojaFisica          0
visitantes_site_mensal             0
aceitou_promocao3                  0
aceitou_promocao4                  0
aceitou_promocao5                  0
aceitou_promocao1                  0
aceitou_promocao2                  0
reclamacao_2anos                   0
custo_cupon_desconto               0
receita                            0
aceitou_ultima_campanha            0
Escolaridade_bkp                   0
Estado_civil_bkp                   0
dtype: int64

In [ ]:
sorted(pd.unique(df2['renda_anual']))

[1730.0,
 2447.0,
 5648.0,
 7500.0,
 9548.0,
 10245.0,
 10404.0,
 10979.0,
 12571.0,
 14045.0,
 14515.0,
 14849.0,
 15033.0,
 15287.0,
 15345.0,
 16248.0,
 16626.0,
 17323.0,
 18100.0,
 18492.0,
 18589.0,
 18701.0,
 18890.0,
 19510.0,
 19789.0,
 19986.0,
 20130.0,
 20518.0,
 20559.0,
 21918.0,
 21994.0,
 22010.0,
 22070.0,
 22212.0,
 22574.0,
 22585.0,
 22804.0,
 23228.0,
 23295.0,
 23442.0,
 23559.0,
 23616.0,
 23626.0,
 23661.0,
 23718.0,
 23957.0,
 23976.0,
 24027.0,
 24072.0,
 24279.0,
 24480.0,
 24594.0,
 24882.0,
 25271.0,
 25545.0,
 25721.0,
 26091.0,
 26095.0,
 26304.0,
 26326.0,
 26490.0,
 26646.0,
 27038.0,
 27190.0,
 27203.0,
 27213.0,
 27255.0,
 27421.0,
 27938.0,
 28249.0,
 28332.0,
 28442.0,
 28457.0,
 28691.0,
 28718.0,
 28839.0,
 29315.0,
 29440.0,
 29548.0,
 29604.0,
 29672.0,
 29760.0,
 29938.0,
 29999.0,
 30015.0,
 30096.0,
 30279.0,
 30351.0,
 30372.0,
 30477.0,
 30507.0,
 30523.0,
 30630.0,
 30631.0,
 30675.0,
 30732.0,
 30753.0,
 30822.0,
 30833.0,
 30899.0,
 30992.0,
 31160.0,
 31353.0,
 31395.0,
 31615.0,
 31686.0,
 31788.0,
 31880.0,
 32011.0,
 32233.0,
 32303.0,
 32414.0,
 32474.0,
 32557.0,
 32880.0,
 33181.0,
 33183.0,
 33378.0,
 33454.0,
 33456.0,
 33581.0,
 33762.0,
 33812.0,
 33996.0,
 34176.0,
 34320.0,
 34421.0,
 34554.0,
 34935.0,
 35178.0,
 35246.0,
 35388.0,
 35416.0,
 35684.0,
 35688.0,
 35790.0,
 35860.0,
 36138.0,
 36143.0,
 36230.0,
 36443.0,
 36550.0,
 36640.0,
 36921.0,
 37040.0,
 37070.0,
 37401.0,
 37406.0,
 37717.0,
 37760.0,
 38097.0,
 38179.0,
 38285.0,
 38360.0,
 38361.0,
 38415.0,
 38547.0,
 38557.0,
 38578.0,
 38590.0,
 38620.0,
 38643.0,
 38823.0,
 38853.0,
 38872.0,
 38961.0,
 38988.0,
 39665.0,
 39747.0,
 40246.0,
 40321.0,
 40464.0,
 40548.0,
 40637.0,
 40689.0,
 40737.0,
 41124.0,
 41411.0,
 41443.0,
 41551.0,
 41644.0,
 41728.0,
 41850.0,
 41883.0,
 42011.0,
 42207.0,
 42373.0,
 42386.0,
 42387.0,
 42394.0,
 42429.0,
 42618.0,
 42670.0,
 42691.0,
 43057.0,
 43482.0,
 43776.0,
 43795.0,
 43824.0,
 43974.0,
 44124.0,
 44159.0,
 44300.0,
 44319.0,
 44377.0,
 44551.0,
 44794.0,
 45204.0,
 45759.0,
 45989.0,
 46014.0,
 46097.0,
 46098.0,
 46310.0,
 46344.0,
 46377.0,
 46610.0,
 46681.0,
 46854.0,
 46923.0,
 47025.0,
 47823.0,
 47916.0,
 48006.0,
 48178.0,
 48330.0,
 48686.0,
 48721.0,
 48920.0,
 48948.0,
 49096.0,
 49269.0,
 49389.0,
 49505.0,
 49605.0,
 49967.0,
 50150.0,
 50300.0,
 50353.0,
 50388.0,
 50437.0,
 50447.0,
 50520.0,
 50737.0,
 50785.0,
 50898.0,
 50943.0,
 51012.0,
 51148.0,
 51369.0,
 51479.0,
 51529.0,
 51537.0,
 51650.0,
 51813.0,
 52074.0,
 52195.0,
 52332.0,
 52413.0,
 52614.0,
 53359.0,
 53537.0,
 53653.0,
 53790.0,
 53858.0,
 54178.0,
 54198.0,
 54348.0,
 54432.0,
 54803.0,
 55212.0,
 55375.0,
 55521.0,
 55563.0,
 55614.0,
 55635.0,
 55707.0,
 55842.0,
 55951.0,
 55954.0,
 56046.0,
 56129.0,
 56223.0,
 56796.0,
 56937.0,
 57288.0,
 57912.0,
 57959.0,
 58138.0,
 58293.0,
 58308.0,
 58607.0,
 58821.0,
 59292.0,
 59354.0,
 59432.0,
 59809.0,
 60000.0,
 60093.0,
 60152.0,
 60182.0,
 60199.0,
 60597.0,
 60631.0,
 60714.0,
 61010.0,
 61074.0,
 61250.0,
 61286.0,
 61314.0,
 61331.0,
 61456.0,
 61823.0,
 61839.0,
 61905.0,
 62010.0,
 62187.0,
 62204.0,
 62499.0,
 62503.0,
 62513.0,
 62551.0,
 62745.0,
 62981.0,
 62998.0,
 63342.0,
 63381.0,
 63693.0,
 63810.0,
 63841.0,
 63887.0,
 64100.0,
 64325.0,
 64355.0,
 64497.0,
 64795.0,
 64961.0,
 65031.0,
 65073.0,
 65104.0,
 65176.0,
 65275.0,
 65640.0,
 65665.0,
 65747.0,
 65808.0,
 65846.0,
 65991.0,
 66313.0,
 66334.0,
 66426.0,
 66465.0,
 66503.0,
 66582.0,
 66664.0,
 66835.0,
 66951.0,
 66973.0,
 66991.0,
 67272.0,
 67309.0,
 67546.0,
 67911.0,
 68126.0,
 68352.0,
 68462.0,
 68627.0,
 68655.0,
 68682.0,
 69096.0,
 69142.0,
 69267.0,
 69372.0,
 69508.0,
 69661.0,
 69674.0,
 69759.0,
 69867.0,
 70165.0,
 70356.0,
 70503.0,
 70777.0,
 70829.0,
 70893.0,
 70951.0,
 71113.0,
 71367.0,
 71488.0,
 71613.0,
 nan,
 3502.0,
 4023.0,
 4428.0,
 4861.0,
 5305.0,
 6560.0,
 6835.0,
 7144.0,
 8028.0,
 8820.0,
 8940.0,
 9255.0,
 9722.0,
 11012.0,
 11448.0,
 12393.0,
 13084.0,
 13260.0,
 13533.0,
 13624.0,
 13672.0,
 13724.0,
 14188.0,
 14421.0,
 14661.0,
 14796.0,
 14906.0,
 14918.0,
 15038.0,
 15056.0,
 15072.0,
 15253.0,
 15315.0,
 15716.0,
 15759.0,
 15862.0,
 16005.0,
 16014.0,
 16185.0,
 16269.0,
 16529.0,
 16531.0,
 16581.0,
 16653.0,
 16813.0,
 16860.0,
 16927.0,
 17003.0,
 17117.0,
 17144.0,
 17148.0,
 17256.0,
 17345.0,
 17459.0,
 17487.0,
 17649.0,
 17688.0,
 18169.0,
 18222.0,
 18227.0,
 18351.0,
 18358.0,
 18393.0,
 18690.0,
 18746.0,
 18793.0,
 18929.0,
 18978.0,
 18988.0,
 19107.0,
 19329.0,
 19346.0,
 19414.0,
 19419.0,
 19444.0,
 19485.0,
 19514.0,
 19656.0,
 19740.0,
 20180.0,
 20193.0,
 20194.0,
 20425.0,
 20427.0,
 20491.0,
 20587.0,
 20895.0,
 20981.0,
 21024.0,
 21059.0,
 21063.0,
 21255.0,
 21282.0,
 21355.0,
 21359.0,
 21474.0,
 21645.0,
 21675.0,
 21840.0,
 21846.0,
 21888.0,
 21955.0,
 22063.0,
 22108.0,
 22123.0,
 22148.0,
 22263.0,
 22280.0,
 22304.0,
 22327.0,
 22390.0,
 22419.0,
 22434.0,
 22448.0,
 22507.0,
 22518.0,
 22554.0,
 22634.0,
 22669.0,
 22682.0,
 22701.0,
 22775.0,
 22944.0,
 22979.0,
 23091.0,
 23148.0,
 23162.0,
 23272.0,
 23331.0,
 23477.0,
 23478.0,
 23529.0,
 23536.0,
 23539.0,
 23724.0,
 23748.0,
 23763.0,
 23830.0,
 23910.0,
 24163.0,
 24206.0,
 24221.0,
 24336.0,
 24367.0,
 24401.0,
 24434.0,
 24570.0,
 24639.0,
 24645.0,
 24683.0,
 24711.0,
 24762.0,
 24884.0,
 25008.0,
 25130.0,
 25176.0,
 25224.0,
 25252.0,
 25293.0,
 25315.0,
 25358.0,
 25410.0,
 25443.0,
 25509.0,
 25707.0,
 25804.0,
 25818.0,
 25851.0,
 25930.0,
 25959.0,
 25965.0,
 26067.0,
 26150.0,
 26224.0,
 26228.0,
 26290.0,
 26487.0,
 26518.0,
 26576.0,
 26642.0,
 26751.0,
 26759.0,
 26816.0,
 26850.0,
 26868.0,
 26872.0,
 26877.0,
 26887.0,
 26907.0,
 26954.0,
 26997.0,
 27071.0,
 27100.0,
 27116.0,
 27159.0,
 27161.0,
 27215.0,
 27238.0,
 27242.0,
 27244.0,
 27450.0,
 27469.0,
 27573.0,
 27590.0,
 27683.0,
 27733.0,
 27803.0,
 27889.0,
 27922.0,
 27943.0,
 28071.0,
 28072.0,
 28087.0,
 28164.0,
 28320.0,
 28359.0,
 28389.0,
 28420.0,
 28427.0,
 28440.0,
 28510.0,
 28520.0,
 28567.0,
 28587.0,
 28647.0,
 28764.0,
 28769.0,
 28973.0,
 29009.0,
 29103.0,
 29187.0,
 29236.0,
 29298.0,
 29435.0,
 29478.0,
 29543.0,
 29732.0,
 29791.0,
 29819.0,
 30023.0,
 30081.0,
 30093.0,
 30168.0,
 30261.0,
 30298.0,
 30368.0,
 30390.0,
 30396.0,
 30467.0,
 30522.0,
 30538.0,
 30545.0,
 30560.0,
 30772.0,
 30801.0,
 30828.0,
 30843.0,
 30983.0,
 31056.0,
 31086.0,
 31089.0,
 31158.0,
 31163.0,
 31385.0,
 31454.0,
 31497.0,
 31535.0,
 31560.0,
 31590.0,
 31605.0,
 31626.0,
 31632.0,
 31761.0,
 31814.0,
 31859.0,
 31878.0,
 31907.0,
 31928.0,
 32144.0,
 32146.0,
 32173.0,
 32218.0,
 32300.0,
 32313.0,
 32583.0,
 32632.0,
 32644.0,
 32727.0,
 32765.0,
 32871.0,
 32889.0,
 32892.0,
 32952.0,
 33039.0,
 33051.0,
 33168.0,
 33178.0,
 33228.0,
 33235.0,
 33249.0,
 33279.0,
 33316.0,
 33402.0,
 33419.0,
 33438.0,
 33444.0,
 33462.0,
 33471.0,
 33562.0,
 33564.0,
 33569.0,
 33585.0,
 33590.0,
 33622.0,
 33629.0,
 33697.0,
 33955.0,
 33986.0,
 34026.0,
 34043.0,
 34053.0,
 34074.0,
 34109.0,
 34213.0,
 34230.0,
 34242.0,
 34350.0,
 34377.0,
 34380.0,
 34412.0,
 34445.0,
 34469.0,
 34487.0,
 34529.0,
 34578.0,
 34587.0,
 34596.0,
 34600.0,
 34633.0,
 34704.0,
 34728.0,
 34738.0,
 34824.0,
 34838.0,
 34853.0,
 34916.0,
 34941.0,
 34961.0,
 34968.0,
 34984.0,
 35196.0,
 35322.0,
 35340.0,
 35441.0,
 35523.0,
 35544.0,
 35641.0,
 35682.0,
 35701.0,
 35704.0,
 35765.0,
 35788.0,
 35791.0,
 35797.0,
 35876.0,
 35893.0,
 35924.0,
 35946.0,
 36026.0,
 36038.0,
 36065.0,
 36075.0,
 36108.0,
 36130.0,
 36145.0,
 36262.0,
 36273.0,
 36283.0,
 36301.0,
 36317.0,
 36408.0,
 36627.0,
 36634.0,
 36663.0,
 36715.0,
 36732.0,
 36736.0,
 36778.0,
 36781.0,
 36790.0,
 36802.0,
 36807.0,
 36864.0,
 36927.0,
 36930.0,
 36947.0,
 36957.0,
 36959.0,
 36975.0,
 36997.0,
 37054.0,
 37085.0,
 37087.0,
 37126.0,
 37150.0,
 37155.0,
 37235.0,
 37244.0,
 37284.0,
 37292.0,
 37334.0,
 37368.0,
 37395.0,
 37509.0,
 37633.0,
 37697.0,
 37716.0,
 37758.0,
 37774.0,
 37787.0,
 37859.0,
 37929.0,
 37971.0,
 38054.0,
 38136.0,
 38175.0,
 38196.0,
 38197.0,
 38200.0,
 38201.0,
 38232.0,
 38236.0,
 38410.0,
 38443.0,
 38452.0,
 38508.0,
 38513.0,
 38576.0,
 38593.0,
 38680.0,
 38683.0,
 38702.0,
 38725.0,
 38741.0,
 38808.0,
 38829.0,
 38887.0,
 38946.0,
 38998.0,
 39062.0,
 39146.0,
 39190.0,
 39228.0,
 39356.0,
 39435.0,
 39453.0,
 39548.0,
 39552.0,
 39660.0,
 39684.0,
 39722.0,
 39763.0,
 39767.0,
 39771.0,
 39791.0,
 39858.0,
 39898.0,
 39922.0,
 39996.0,
 40049.0,
 40059.0,
 40101.0,
 40211.0,
 40233.0,
 40304.0,
 40344.0,
 40442.0,
 40451.0,
 40479.0,
 40521.0,
 40590.0,
 40662.0,
 40706.0,
 40760.0,
 40780.0,
 40794.0,
 40800.0,
 40851.0,
 40887.0,
 41003.0,
 41014.0,
 41020.0,
 41021.0,
 41039.0,
 41120.0,
 41145.0,
 41154.0,
 41275.0,
 41335.0,
 41437.0,
 41452.0,
 41473.0,
 41580.0,
 41638.0,
 41658.0,
 41713.0,
 41769.0,
 41967.0,
 41986.0,
 42000.0,
 42014.0,
 42021.0,
 42033.0,
 42081.0,
 42160.0,
 42162.0,
 42169.0,
 42192.0,
 42213.0,
 42231.0,
 42243.0,
 42315.0,
 42395.0,
 42403.0,
 42473.0,
 42523.0,
 42554.0,
 42557.0,
 42564.0,
 42586.0,
 42607.0,
 42664.0,
 42693.0,
 42710.0,
 42720.0,
 42731.0,
 42767.0,
 42769.0,
 42835.0,
 42873.0,
 42997.0,
 43018.0,
 43020.0,
 43050.0,
 43140.0,
 43142.0,
 43185.0,
 43263.0,
 43269.0,
 43300.0,
 43322.0,
 43456.0,
 43462.0,
 43586.0,
 43602.0,
 43638.0,
 43641.0,
 43783.0,
 43815.0,
 44010.0,
 44051.0,
 44078.0,
 44155.0,
 44213.0,
 44267.0,
 44322.0,
 44325.0,
 44359.0,
 44375.0,
 44392.0,
 44393.0,
 44421.0,
 44503.0,
 44511.0,
 44512.0,
 44529.0,
 44602.0,
 44635.0,
 44689.0,
 44802.0,
 44911.0,
 44931.0,
 44953.0,
 44964.0,
 44989.0,
 45006.0,
 45057.0,
 45068.0,
 45072.0,
 45143.0,
 45146.0,
 45160.0,
 45183.0,
 45203.0,
 45207.0,
 45503.0,
 45576.0,
 45579.0,
 45684.0,
 45688.0,
 45736.0,
 45837.0,
 45889.0,
 45894.0,
 45903.0,
 45906.0,
 45921.0,
 45938.0,
 46015.0,
 46049.0,
 ...]

Abaixo estou conferindo algumas colunas para saber se deleto ou não

In [ ]:
sorted(pd.unique(df2['receita']))

[11]

In [ ]:
df2.identificacao.is_unique

True

In [ ]:
display(df2.custo_cupon_desconto.is_unique)
display(sorted(pd.unique(df2['custo_cupon_desconto'])))

False

[3]

In [ ]:
sorted(pd.unique(df2['qtd_descontos_feitos']))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15]

In [ ]:
'''
 DELETAR COLUNAS

A coluna Receita retorna apenas o numero 11 em toda sua extensão,
 sendo irrelevante se pra todos é o mesmo valor

 o ID (identificacao) do cliente não se repete, mas vou deixa-la para
 fazer JOINS logo a frente. 

A coluna custo_cupon_desconto possui apenas o mesmo valor, mesmo apresentando não ser 
coluna de valor unico, portanto também será retirada.

Como a coluna qtd_descontos_feitos é a soma das vezes que  cliente aceitou as
promoções / campanhas realizadas, então todas as colunas que falam sobre campanha
1-2-3-4-5 tornam-se desnecessárias nesta análise em questão.


'''

'\n DELETAR COLUNAS\n\nA coluna Receita retorna apenas o numero 11 em toda sua extensão,\n sendo irrelevante se pra todos é o mesmo valor\n\n o ID (identificacao) do cliente não se repete, mas vou deixa-la para\n fazer JOINS logo a frente. \n\nA coluna custo_cupon_desconto possui apenas o mesmo valor, mesmo apresentando não ser \ncoluna de valor unico, portanto também será retirada.\n\nComo a coluna qtd_descontos_feitos é a soma das vezes que  cliente aceitou as\npromoções / campanhas realizadas, então todas as colunas que falam sobre campanha\n1-2-3-4-5 tornam-se desnecessárias nesta análise em questão.\n\n\n'

In [ ]:
# DROP DE COLUNA DESNECESSÁRIA
df2.drop(['receita', 'custo_cupon_desconto', 'aceitou_promocao1', 'aceitou_promocao2', 'aceitou_promocao3', 'aceitou_promocao4', 'aceitou_promocao5', 'aceitou_ultima_campanha'],axis=1,inplace=True)

In [ ]:
'''
As colunas de tradução também foram um sucesso, ja 
posso dropar as colunas de backup
'''

df2.drop(['Escolaridade_bkp', 'Estado_civil_bkp'],axis=1,inplace=True)

In [ ]:
# TRATAMENTO DOS NULOS
'''
Apenas 1 coluna apresentou valores nulos, vou agora conferir
o que esta acontecendo e padronizar os valores,
visto que se trata de renda anual do cliente, fica mais fidedigno um resultado
nulo ou apagado do que um resultado falso (como 0 ou a média dos valores por exemplo).
'''

sorted(pd.unique(df2['renda_anual']))

[1730.0,
 2447.0,
 5648.0,
 7500.0,
 9548.0,
 10245.0,
 10404.0,
 10979.0,
 12571.0,
 14045.0,
 14515.0,
 14849.0,
 15033.0,
 15287.0,
 15345.0,
 16248.0,
 16626.0,
 17323.0,
 18100.0,
 18492.0,
 18589.0,
 18701.0,
 18890.0,
 19510.0,
 19789.0,
 19986.0,
 20130.0,
 20518.0,
 20559.0,
 21918.0,
 21994.0,
 22010.0,
 22070.0,
 22212.0,
 22574.0,
 22585.0,
 22804.0,
 23228.0,
 23295.0,
 23442.0,
 23559.0,
 23616.0,
 23626.0,
 23661.0,
 23718.0,
 23957.0,
 23976.0,
 24027.0,
 24072.0,
 24279.0,
 24480.0,
 24594.0,
 24882.0,
 25271.0,
 25545.0,
 25721.0,
 26091.0,
 26095.0,
 26304.0,
 26326.0,
 26490.0,
 26646.0,
 27038.0,
 27190.0,
 27203.0,
 27213.0,
 27255.0,
 27421.0,
 27938.0,
 28249.0,
 28332.0,
 28442.0,
 28457.0,
 28691.0,
 28718.0,
 28839.0,
 29315.0,
 29440.0,
 29548.0,
 29604.0,
 29672.0,
 29760.0,
 29938.0,
 29999.0,
 30015.0,
 30096.0,
 30279.0,
 30351.0,
 30372.0,
 30477.0,
 30507.0,
 30523.0,
 30630.0,
 30631.0,
 30675.0,
 30732.0,
 30753.0,
 30822.0,
 30833.0,
 30899.0,
 30992.0,
 31160.0,
 31353.0,
 31395.0,
 31615.0,
 31686.0,
 31788.0,
 31880.0,
 32011.0,
 32233.0,
 32303.0,
 32414.0,
 32474.0,
 32557.0,
 32880.0,
 33181.0,
 33183.0,
 33378.0,
 33454.0,
 33456.0,
 33581.0,
 33762.0,
 33812.0,
 33996.0,
 34176.0,
 34320.0,
 34421.0,
 34554.0,
 34935.0,
 35178.0,
 35246.0,
 35388.0,
 35416.0,
 35684.0,
 35688.0,
 35790.0,
 35860.0,
 36138.0,
 36143.0,
 36230.0,
 36443.0,
 36550.0,
 36640.0,
 36921.0,
 37040.0,
 37070.0,
 37401.0,
 37406.0,
 37717.0,
 37760.0,
 38097.0,
 38179.0,
 38285.0,
 38360.0,
 38361.0,
 38415.0,
 38547.0,
 38557.0,
 38578.0,
 38590.0,
 38620.0,
 38643.0,
 38823.0,
 38853.0,
 38872.0,
 38961.0,
 38988.0,
 39665.0,
 39747.0,
 40246.0,
 40321.0,
 40464.0,
 40548.0,
 40637.0,
 40689.0,
 40737.0,
 41124.0,
 41411.0,
 41443.0,
 41551.0,
 41644.0,
 41728.0,
 41850.0,
 41883.0,
 42011.0,
 42207.0,
 42373.0,
 42386.0,
 42387.0,
 42394.0,
 42429.0,
 42618.0,
 42670.0,
 42691.0,
 43057.0,
 43482.0,
 43776.0,
 43795.0,
 43824.0,
 43974.0,
 44124.0,
 44159.0,
 44300.0,
 44319.0,
 44377.0,
 44551.0,
 44794.0,
 45204.0,
 45759.0,
 45989.0,
 46014.0,
 46097.0,
 46098.0,
 46310.0,
 46344.0,
 46377.0,
 46610.0,
 46681.0,
 46854.0,
 46923.0,
 47025.0,
 47823.0,
 47916.0,
 48006.0,
 48178.0,
 48330.0,
 48686.0,
 48721.0,
 48920.0,
 48948.0,
 49096.0,
 49269.0,
 49389.0,
 49505.0,
 49605.0,
 49967.0,
 50150.0,
 50300.0,
 50353.0,
 50388.0,
 50437.0,
 50447.0,
 50520.0,
 50737.0,
 50785.0,
 50898.0,
 50943.0,
 51012.0,
 51148.0,
 51369.0,
 51479.0,
 51529.0,
 51537.0,
 51650.0,
 51813.0,
 52074.0,
 52195.0,
 52332.0,
 52413.0,
 52614.0,
 53359.0,
 53537.0,
 53653.0,
 53790.0,
 53858.0,
 54178.0,
 54198.0,
 54348.0,
 54432.0,
 54803.0,
 55212.0,
 55375.0,
 55521.0,
 55563.0,
 55614.0,
 55635.0,
 55707.0,
 55842.0,
 55951.0,
 55954.0,
 56046.0,
 56129.0,
 56223.0,
 56796.0,
 56937.0,
 57288.0,
 57912.0,
 57959.0,
 58138.0,
 58293.0,
 58308.0,
 58607.0,
 58821.0,
 59292.0,
 59354.0,
 59432.0,
 59809.0,
 60000.0,
 60093.0,
 60152.0,
 60182.0,
 60199.0,
 60597.0,
 60631.0,
 60714.0,
 61010.0,
 61074.0,
 61250.0,
 61286.0,
 61314.0,
 61331.0,
 61456.0,
 61823.0,
 61839.0,
 61905.0,
 62010.0,
 62187.0,
 62204.0,
 62499.0,
 62503.0,
 62513.0,
 62551.0,
 62745.0,
 62981.0,
 62998.0,
 63342.0,
 63381.0,
 63693.0,
 63810.0,
 63841.0,
 63887.0,
 64100.0,
 64325.0,
 64355.0,
 64497.0,
 64795.0,
 64961.0,
 65031.0,
 65073.0,
 65104.0,
 65176.0,
 65275.0,
 65640.0,
 65665.0,
 65747.0,
 65808.0,
 65846.0,
 65991.0,
 66313.0,
 66334.0,
 66426.0,
 66465.0,
 66503.0,
 66582.0,
 66664.0,
 66835.0,
 66951.0,
 66973.0,
 66991.0,
 67272.0,
 67309.0,
 67546.0,
 67911.0,
 68126.0,
 68352.0,
 68462.0,
 68627.0,
 68655.0,
 68682.0,
 69096.0,
 69142.0,
 69267.0,
 69372.0,
 69508.0,
 69661.0,
 69674.0,
 69759.0,
 69867.0,
 70165.0,
 70356.0,
 70503.0,
 70777.0,
 70829.0,
 70893.0,
 70951.0,
 71113.0,
 71367.0,
 71488.0,
 71613.0,
 nan,
 3502.0,
 4023.0,
 4428.0,
 4861.0,
 5305.0,
 6560.0,
 6835.0,
 7144.0,
 8028.0,
 8820.0,
 8940.0,
 9255.0,
 9722.0,
 11012.0,
 11448.0,
 12393.0,
 13084.0,
 13260.0,
 13533.0,
 13624.0,
 13672.0,
 13724.0,
 14188.0,
 14421.0,
 14661.0,
 14796.0,
 14906.0,
 14918.0,
 15038.0,
 15056.0,
 15072.0,
 15253.0,
 15315.0,
 15716.0,
 15759.0,
 15862.0,
 16005.0,
 16014.0,
 16185.0,
 16269.0,
 16529.0,
 16531.0,
 16581.0,
 16653.0,
 16813.0,
 16860.0,
 16927.0,
 17003.0,
 17117.0,
 17144.0,
 17148.0,
 17256.0,
 17345.0,
 17459.0,
 17487.0,
 17649.0,
 17688.0,
 18169.0,
 18222.0,
 18227.0,
 18351.0,
 18358.0,
 18393.0,
 18690.0,
 18746.0,
 18793.0,
 18929.0,
 18978.0,
 18988.0,
 19107.0,
 19329.0,
 19346.0,
 19414.0,
 19419.0,
 19444.0,
 19485.0,
 19514.0,
 19656.0,
 19740.0,
 20180.0,
 20193.0,
 20194.0,
 20425.0,
 20427.0,
 20491.0,
 20587.0,
 20895.0,
 20981.0,
 21024.0,
 21059.0,
 21063.0,
 21255.0,
 21282.0,
 21355.0,
 21359.0,
 21474.0,
 21645.0,
 21675.0,
 21840.0,
 21846.0,
 21888.0,
 21955.0,
 22063.0,
 22108.0,
 22123.0,
 22148.0,
 22263.0,
 22280.0,
 22304.0,
 22327.0,
 22390.0,
 22419.0,
 22434.0,
 22448.0,
 22507.0,
 22518.0,
 22554.0,
 22634.0,
 22669.0,
 22682.0,
 22701.0,
 22775.0,
 22944.0,
 22979.0,
 23091.0,
 23148.0,
 23162.0,
 23272.0,
 23331.0,
 23477.0,
 23478.0,
 23529.0,
 23536.0,
 23539.0,
 23724.0,
 23748.0,
 23763.0,
 23830.0,
 23910.0,
 24163.0,
 24206.0,
 24221.0,
 24336.0,
 24367.0,
 24401.0,
 24434.0,
 24570.0,
 24639.0,
 24645.0,
 24683.0,
 24711.0,
 24762.0,
 24884.0,
 25008.0,
 25130.0,
 25176.0,
 25224.0,
 25252.0,
 25293.0,
 25315.0,
 25358.0,
 25410.0,
 25443.0,
 25509.0,
 25707.0,
 25804.0,
 25818.0,
 25851.0,
 25930.0,
 25959.0,
 25965.0,
 26067.0,
 26150.0,
 26224.0,
 26228.0,
 26290.0,
 26487.0,
 26518.0,
 26576.0,
 26642.0,
 26751.0,
 26759.0,
 26816.0,
 26850.0,
 26868.0,
 26872.0,
 26877.0,
 26887.0,
 26907.0,
 26954.0,
 26997.0,
 27071.0,
 27100.0,
 27116.0,
 27159.0,
 27161.0,
 27215.0,
 27238.0,
 27242.0,
 27244.0,
 27450.0,
 27469.0,
 27573.0,
 27590.0,
 27683.0,
 27733.0,
 27803.0,
 27889.0,
 27922.0,
 27943.0,
 28071.0,
 28072.0,
 28087.0,
 28164.0,
 28320.0,
 28359.0,
 28389.0,
 28420.0,
 28427.0,
 28440.0,
 28510.0,
 28520.0,
 28567.0,
 28587.0,
 28647.0,
 28764.0,
 28769.0,
 28973.0,
 29009.0,
 29103.0,
 29187.0,
 29236.0,
 29298.0,
 29435.0,
 29478.0,
 29543.0,
 29732.0,
 29791.0,
 29819.0,
 30023.0,
 30081.0,
 30093.0,
 30168.0,
 30261.0,
 30298.0,
 30368.0,
 30390.0,
 30396.0,
 30467.0,
 30522.0,
 30538.0,
 30545.0,
 30560.0,
 30772.0,
 30801.0,
 30828.0,
 30843.0,
 30983.0,
 31056.0,
 31086.0,
 31089.0,
 31158.0,
 31163.0,
 31385.0,
 31454.0,
 31497.0,
 31535.0,
 31560.0,
 31590.0,
 31605.0,
 31626.0,
 31632.0,
 31761.0,
 31814.0,
 31859.0,
 31878.0,
 31907.0,
 31928.0,
 32144.0,
 32146.0,
 32173.0,
 32218.0,
 32300.0,
 32313.0,
 32583.0,
 32632.0,
 32644.0,
 32727.0,
 32765.0,
 32871.0,
 32889.0,
 32892.0,
 32952.0,
 33039.0,
 33051.0,
 33168.0,
 33178.0,
 33228.0,
 33235.0,
 33249.0,
 33279.0,
 33316.0,
 33402.0,
 33419.0,
 33438.0,
 33444.0,
 33462.0,
 33471.0,
 33562.0,
 33564.0,
 33569.0,
 33585.0,
 33590.0,
 33622.0,
 33629.0,
 33697.0,
 33955.0,
 33986.0,
 34026.0,
 34043.0,
 34053.0,
 34074.0,
 34109.0,
 34213.0,
 34230.0,
 34242.0,
 34350.0,
 34377.0,
 34380.0,
 34412.0,
 34445.0,
 34469.0,
 34487.0,
 34529.0,
 34578.0,
 34587.0,
 34596.0,
 34600.0,
 34633.0,
 34704.0,
 34728.0,
 34738.0,
 34824.0,
 34838.0,
 34853.0,
 34916.0,
 34941.0,
 34961.0,
 34968.0,
 34984.0,
 35196.0,
 35322.0,
 35340.0,
 35441.0,
 35523.0,
 35544.0,
 35641.0,
 35682.0,
 35701.0,
 35704.0,
 35765.0,
 35788.0,
 35791.0,
 35797.0,
 35876.0,
 35893.0,
 35924.0,
 35946.0,
 36026.0,
 36038.0,
 36065.0,
 36075.0,
 36108.0,
 36130.0,
 36145.0,
 36262.0,
 36273.0,
 36283.0,
 36301.0,
 36317.0,
 36408.0,
 36627.0,
 36634.0,
 36663.0,
 36715.0,
 36732.0,
 36736.0,
 36778.0,
 36781.0,
 36790.0,
 36802.0,
 36807.0,
 36864.0,
 36927.0,
 36930.0,
 36947.0,
 36957.0,
 36959.0,
 36975.0,
 36997.0,
 37054.0,
 37085.0,
 37087.0,
 37126.0,
 37150.0,
 37155.0,
 37235.0,
 37244.0,
 37284.0,
 37292.0,
 37334.0,
 37368.0,
 37395.0,
 37509.0,
 37633.0,
 37697.0,
 37716.0,
 37758.0,
 37774.0,
 37787.0,
 37859.0,
 37929.0,
 37971.0,
 38054.0,
 38136.0,
 38175.0,
 38196.0,
 38197.0,
 38200.0,
 38201.0,
 38232.0,
 38236.0,
 38410.0,
 38443.0,
 38452.0,
 38508.0,
 38513.0,
 38576.0,
 38593.0,
 38680.0,
 38683.0,
 38702.0,
 38725.0,
 38741.0,
 38808.0,
 38829.0,
 38887.0,
 38946.0,
 38998.0,
 39062.0,
 39146.0,
 39190.0,
 39228.0,
 39356.0,
 39435.0,
 39453.0,
 39548.0,
 39552.0,
 39660.0,
 39684.0,
 39722.0,
 39763.0,
 39767.0,
 39771.0,
 39791.0,
 39858.0,
 39898.0,
 39922.0,
 39996.0,
 40049.0,
 40059.0,
 40101.0,
 40211.0,
 40233.0,
 40304.0,
 40344.0,
 40442.0,
 40451.0,
 40479.0,
 40521.0,
 40590.0,
 40662.0,
 40706.0,
 40760.0,
 40780.0,
 40794.0,
 40800.0,
 40851.0,
 40887.0,
 41003.0,
 41014.0,
 41020.0,
 41021.0,
 41039.0,
 41120.0,
 41145.0,
 41154.0,
 41275.0,
 41335.0,
 41437.0,
 41452.0,
 41473.0,
 41580.0,
 41638.0,
 41658.0,
 41713.0,
 41769.0,
 41967.0,
 41986.0,
 42000.0,
 42014.0,
 42021.0,
 42033.0,
 42081.0,
 42160.0,
 42162.0,
 42169.0,
 42192.0,
 42213.0,
 42231.0,
 42243.0,
 42315.0,
 42395.0,
 42403.0,
 42473.0,
 42523.0,
 42554.0,
 42557.0,
 42564.0,
 42586.0,
 42607.0,
 42664.0,
 42693.0,
 42710.0,
 42720.0,
 42731.0,
 42767.0,
 42769.0,
 42835.0,
 42873.0,
 42997.0,
 43018.0,
 43020.0,
 43050.0,
 43140.0,
 43142.0,
 43185.0,
 43263.0,
 43269.0,
 43300.0,
 43322.0,
 43456.0,
 43462.0,
 43586.0,
 43602.0,
 43638.0,
 43641.0,
 43783.0,
 43815.0,
 44010.0,
 44051.0,
 44078.0,
 44155.0,
 44213.0,
 44267.0,
 44322.0,
 44325.0,
 44359.0,
 44375.0,
 44392.0,
 44393.0,
 44421.0,
 44503.0,
 44511.0,
 44512.0,
 44529.0,
 44602.0,
 44635.0,
 44689.0,
 44802.0,
 44911.0,
 44931.0,
 44953.0,
 44964.0,
 44989.0,
 45006.0,
 45057.0,
 45068.0,
 45072.0,
 45143.0,
 45146.0,
 45160.0,
 45183.0,
 45203.0,
 45207.0,
 45503.0,
 45576.0,
 45579.0,
 45684.0,
 45688.0,
 45736.0,
 45837.0,
 45889.0,
 45894.0,
 45903.0,
 45906.0,
 45921.0,
 45938.0,
 46015.0,
 46049.0,
 ...]

In [ ]:
'''
O valor encontrado foi nan (Not a Number), mas ele vai atrapalhar minhas análises,
portanto vou excluir a linha toda que tiver NaN.

'''

df2.dropna(axis=0, inplace=True)

Rode o comando anterior (Sorted) para verificar se o valor nan saiu da lista.

In [ ]:
# CONFERINDO COMO FICOU NOSSO DATAFRAME

display(df2)

,identificacao,ano_nascimento,escolaridade,estado_civil,renda_anual,num_criancas_casa,num_adolescentes_casa,cliente_desde,dias_ultima_compra,gasto_com_vinho_2ultimos_anos,...,gasto_com_carnes_2ultimos_anos,gasto_com_peixes_2ultimos_anos,gasto_com_doces_2ultimos_anos,gasto_com_ouro_2ultimos_anos,qtd_descontos_feitos,compras_pela_internet,compras_usando_catalago,compras_feitas_lojaFisica,visitantes_site_mensal,reclamacao_2anos
0,5524,1957,Bacharel,Solteira(o),58138.0,0,0,04-09-2012,58,635,...,546,172,88,88,3,8,10,4,7,0
1,2174,1954,Bacharel,Solteira(o),46344.0,1,1,08-03-2014,38,11,...,6,2,1,6,2,1,1,2,5,0
2,4141,1965,Bacharel,Uniao_Estavel,71613.0,0,0,21-08-2013,26,426,...,127,111,21,42,1,8,2,10,4,0
3,6182,1984,Bacharel,Uniao_Estavel,26646.0,1,0,10-02-2014,26,11,...,20,10,3,5,2,2,0,4,6,0
4,5324,1981,Doutorado,Casado(a),58293.0,1,0,19-01-2014,94,173,...,118,46,27,15,5,5,3,6,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Bacharel,Casado(a),61223.0,0,1,13-06-2013,46,709,...,182,42,118,247,2,9,3,4,5,0
2236,4001,1946,Doutorado,Uniao_Estavel,64014.0,2,1,10-06-2014,56,406,...,30,0,0,8,7,8,2,5,7,0
2237,7270,1981,Bacharel,Divorciada(o),56981.0,0,0,25-01-2014,91,908,...,217,32,12,24,1,2,3,13,6,0
2238,8235,1956,Mestrado,Uniao_Estavel,69245.0,0,1,24-01-2014,8,428,...,214,80,30,61,2,6,5,10,3,0
2239,9405,1954,Doutorado,Casado(a),52869.0,1,1,15-10-2012,40,84,...,61,2,1,21,3,3,1,4,7,0

## VALIDANDO OS VALORES

Antes de passar para o Pyspark, achei interessante validar o tipo de cada coluna pra String, Flot, Inteiro ou Datetime, pra não precisar tratar "Object" no Pyspark.

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2216 entries, 0 to 2239
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   identificacao                   2216 non-null   int64
 1   ano_nascimento                  2216 non-null   int64
 2   escolaridade                    2216 non-null   object
 3   estado_civil                    2216 non-null   object
 4   renda_anual                     2216 non-null   float64
 5   num_criancas_casa               2216 non-null   int64
 6   num_adolescentes_casa           2216 non-null   int64
 7   cliente_desde                   2216 non-null   object
 8   dias_ultima_compra              2216 non-null   int64
 9   gasto_com_vinho_2ultimos_anos   2216 non-null   int64
 10  gasto_com_frutas_2ultimos_anos  2216 non-null   int64
 11  gasto_com_carnes_2ultimos_anos  2216 non-null   int64
 12  gasto_com_peixes_2ultimos_anos  2216 non-null   int64
 13  gasto_com_doces_2ultimos_anos   2216 non-null   int64
 14  gasto_com_ouro_2ultimos_anos    2216 non-null   int64
 15  qtd_descontos_feitos            2216 non-null   int64
 16  compras_pela_internet           2216 non-null   int64
 17  compras_usando_catalago         2216 non-null   int64
 18  compras_feitas_lojaFisica       2216 non-null   int64
 19  visitantes_site_mensal          2216 non-null   int64
 20  reclamacao_2anos                2216 non-null   int64
dtypes: float64(1), int64(17), object(3)
memory usage: 380.9+ KB

In [ ]:
schemaPANDERA = pa.DataFrameSchema(
    columns = {
        "ano_nascimento":pa.Column(pa.Int),
        "escolaridade":pa.Column(pa.String),
        "estado_civil":pa.Column(pa.String),
        "renda_anual":pa.Column(pa.Float, nullable=True),
        "num_criancas_casa":pa.Column(pa.Int),
        "num_adolescentes_casa":pa.Column(pa.Int),
        "cliente_desde":pa.Column(pa.String),
        "dias_ultima_compra":pa.Column(pa.Int),
        "gasto_com_vinho_2ultimos_anos":pa.Column(pa.Int),
        "gasto_com_frutas_2ultimos_anos":pa.Column(pa.Int),
        "gasto_com_carnes_2ultimos_anos":pa.Column(pa.Int),
        "gasto_com_peixes_2ultimos_anos":pa.Column(pa.Int),
        "gasto_com_doces_2ultimos_anos":pa.Column(pa.Int),
        "gasto_com_ouro_2ultimos_anos":pa.Column(pa.Int),
        "qtd_descontos_feitos":pa.Column(pa.Int),
        "compras_pela_internet":pa.Column(pa.Int),
        "compras_usando_catalago":pa.Column(pa.Int),
        "compras_feitas_lojaFisica":pa.Column(pa.Int),
        "visitantes_site_mensal":pa.Column(pa.Int),
        "reclamacao_2anos":pa.Column(pa.Int)
    }
)

In [ ]:
'''
O ano_nascimento deixei como inteiro porque é apenas o ano, sendo só os 4 dígitos;
A renda_anual mantive o nullable = True porque possui valores nulos
Na coluna cliente_desde deixei com String porque como DateTime dava erro;
As demais colunas estão Inteiro porque respondem com valores inteiros.
'''

'\nO ano_nascimento deixei como inteiro porque é apenas o ano, sendo só os 4 dígitos;\nA renda_anual mantive o nullable = True porque possui valores nulos\nNa coluna cliente_desde deixei com String porque como DateTime dava erro;\nAs demais colunas estão Inteiro porque respondem com valores inteiros.\n'

In [ ]:
schemaPANDERA.validate(df2)

,identificacao,ano_nascimento,escolaridade,estado_civil,renda_anual,num_criancas_casa,num_adolescentes_casa,cliente_desde,dias_ultima_compra,gasto_com_vinho_2ultimos_anos,...,gasto_com_carnes_2ultimos_anos,gasto_com_peixes_2ultimos_anos,gasto_com_doces_2ultimos_anos,gasto_com_ouro_2ultimos_anos,qtd_descontos_feitos,compras_pela_internet,compras_usando_catalago,compras_feitas_lojaFisica,visitantes_site_mensal,reclamacao_2anos
0,5524,1957,Bacharel,Solteira(o),58138.0,0,0,04-09-2012,58,635,...,546,172,88,88,3,8,10,4,7,0
1,2174,1954,Bacharel,Solteira(o),46344.0,1,1,08-03-2014,38,11,...,6,2,1,6,2,1,1,2,5,0
2,4141,1965,Bacharel,Uniao_Estavel,71613.0,0,0,21-08-2013,26,426,...,127,111,21,42,1,8,2,10,4,0
3,6182,1984,Bacharel,Uniao_Estavel,26646.0,1,0,10-02-2014,26,11,...,20,10,3,5,2,2,0,4,6,0
4,5324,1981,Doutorado,Casado(a),58293.0,1,0,19-01-2014,94,173,...,118,46,27,15,5,5,3,6,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Bacharel,Casado(a),61223.0,0,1,13-06-2013,46,709,...,182,42,118,247,2,9,3,4,5,0
2236,4001,1946,Doutorado,Uniao_Estavel,64014.0,2,1,10-06-2014,56,406,...,30,0,0,8,7,8,2,5,7,0
2237,7270,1981,Bacharel,Divorciada(o),56981.0,0,0,25-01-2014,91,908,...,217,32,12,24,1,2,3,13,6,0
2238,8235,1956,Mestrado,Uniao_Estavel,69245.0,0,1,24-01-2014,8,428,...,214,80,30,61,2,6,5,10,3,0
2239,9405,1954,Doutorado,Casado(a),52869.0,1,1,15-10-2012,40,84,...,61,2,1,21,3,3,1,4,7,0

## PYSPARK

In [ ]:
# CONSTRUIR MINHA SPARK SESSION 

spark = (
    SparkSession.builder
                .master('local')
                .appName('projeto_individual')
                .config('spark.ui.port', '4050')
                .getOrCreate()
)

display(spark)

In [ ]:
# CRIANDO DATAFRAME NO PYSPARK PUXANDO DO PANDAS (DF2)
'''
VOU CRIAR UM TERCEIRO DF A PARTIR DO QUE JA FOI TRATADO EM PANDAS,
ASSIM TENHO UM SEGUNDO BACKUP TAMBÉM
'''

df3 = spark.createDataFrame(df2)

df3.show(20)

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+-----------------------------+------------------------------+------------------------------+------------------------------+-----------------------------+----------------------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|gasto_com_vinho_2ultimos_anos|gasto_com_frutas_2ultimos_anos|gasto_com_carnes_2ultimos_anos|gasto_com_peixes_2ultimos_anos|gasto_com_doces_2ultimos_anos|gasto_com_ouro_2ultimos_anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|reclamacao_2anos|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+-----------------------------+------------------------------+------------------------------+------------------------------+-----------------------------+----------------------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+
|         5524|          1957|    Bacharel|  Solteira(o)|    58138.0|                0|                    0|   04-09-2012|                58|                          635|                            88|                           546|                           172|                           88|                          88|                   3|                    8|                     10|                        4|                     7|               0|
|         2174|          1954|    Bacharel|  Solteira(o)|    46344.0|                1|                    1|   08-03-2014|                38|                           11|                             1|                             6|                             2|                            1|                           6|                   2|                    1|                      1|                        2|                     5|               0|
|         4141|          1965|    Bacharel|Uniao_Estavel|    71613.0|                0|                    0|   21-08-2013|                26|                          426|                            49|                           127|                           111|                           21|                          42|                   1|                    8|                      2|                       10|                     4|               0|
|         6182|          1984|    Bacharel|Uniao_Estavel|    26646.0|                1|                    0|   10-02-2014|                26|                           11|                             4|                            20|                            10|                            3|                           5|                   2|                    2|                      0|                        4|                     6|               0|
|         5324|          1981|   Doutorado|    Casado(a)|    58293.0|                1|                    0|   19-01-2014|                94|                          173|                            43|                           118|                            46|                           27|                          15|                   5|                    5|                      3|                        6|                     5|               0|
|         7446|          1967|    Mestrado|Uniao_Estavel|    62513.0|                0|                    1|   09-09-2013|                16|                          520|                            42|                            98|                             0|                           42|                          14|                   2|                    6|                      4|                       10|                     6|               0|
|          965|          1971|    Bacharel|Divorciada(o)|    55635.0|                0|                    1|   13-11-2012|                34|                          235|                            65|                           164|                            50|                           49|                          27|                   4|                    7|                      3|                        7|                     6|               0|
|         6177|          1985|   Doutorado|    Casado(a)|    33454.0|                1|                    0|   08-05-2013|                32|                           76|                            10|                            56|                             3|                            1|                          23|                   2|                    4|                      0|                        4|                     8|               0|
|         4855|          1974|   Doutorado|Uniao_Estavel|    30351.0|                1|                    0|   06-06-2013|                19|                           14|                             0|                            24|                             3|                            3|                           2|                   1|                    3|                      0|                        2|                     9|               0|
|         5899|          1950|   Doutorado|Uniao_Estavel|     5648.0|                1|                    1|   13-03-2014|                68|                           28|                             0|                             6|                             1|                            1|                          13|                   1|                    1|                      0|                        0|                    20|               0|
|          387|          1976| Fundamental|    Casado(a)|     7500.0|                0|                    0|   13-11-2012|                59|                            6|                            16|                            11|                            11|                            1|                          16|                   1|                    2|                      0|                        3|                     8|               0|
|         2125|          1959|    Bacharel|Divorciada(o)|    63033.0|                0|                    0|   15-11-2013|                82|                          194|                            61|                           480|                           225|                          112|                          30|                   1|                    3|                      4|                        8|                     2|               0|
|         8180|          1952|    Mestrado|Divorciada(o)|    59354.0|                1|                    1|   15-11-2013|                53|                          233|                             2|                            53|                             3|                            5|                          14|                   3|                    6|                      1|                        5|                     6|               0|
|         2569|          1987|    Bacharel|    Casado(a)|    17323.0|                0|                    0|   10-10-2012|                38|                            3|                            14|                            17|                             6|                            1|                           5|                   1|                    1|                      0|                        3|                     8|               0|
|         2114|          1946|   Doutorado|  Solteira(o)|    82800.0|                0|                    0|   24-11-2012|                23|                         1006|                            22|                           115|                            59|                           68|                          45|                   1|                    7|                      6|                       12|                     3|               0|
|         9736|          1980|    Bacharel|    Casado(a)|    41850.0|                1|                    1|   24-12-2012|                51|                           53|                             5|                            19|                             2|                           13|                           4|                   3|                    3|                      0|                        3|                     8|               0|
|         4939|          1946|    Bacharel|Uniao_Estavel|    37760.0|                0|                    0|   31-08-2012|                20|                           84|                             5|                            38|                           150|                           12|                          28|                   2|                    4|                      1|                        6|                     7|               0|
|         6565|          1949|    Mestrado|    Casado(a)|    76995.0|                0|                    1|   28-03-2013|                91|                         1012|                            80|                           498|                             0|                           16|                         176|                   2|                   11|                      4|                        9|                     5|               0|
|         2278|          1985|Pos-graduado|  Solteira(o)|    33812.0|                1|                    0|   03-11-2012|                86|                            4|                            17|                            19|                            30|                           24|                          39|                   2|                    2|                      1|                        3|                     6|               0|
|         9360|          1982|    Bacharel|    Casado(a)|    37040.0|                0|                    0|   08-08-2012|                41|                           86|                             2|                            73|                            69|                           38|                          48|                   1|                    4|                      2|                        5|                     8|               0|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+-----------------------------+------------------------------+------------------------------+------------------------------+-----------------------------+----------------------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+
only showing top 20 rows

In [ ]:
# COMO VOU CRIAR UM STRUCTTYPE, PRECISO SABER O TIPO DE CADA COLUNA E SE ELAS SÃO NULL ABLE

df3.printSchema()

root
 |-- identificacao: long (nullable = true)
 |-- ano_nascimento: long (nullable = true)
 |-- escolaridade: string (nullable = true)
 |-- estado_civil: string (nullable = true)
 |-- renda_anual: double (nullable = true)
 |-- num_criancas_casa: long (nullable = true)
 |-- num_adolescentes_casa: long (nullable = true)
 |-- cliente_desde: string (nullable = true)
 |-- dias_ultima_compra: long (nullable = true)
 |-- gasto_com_vinho_2ultimos_anos: long (nullable = true)
 |-- gasto_com_frutas_2ultimos_anos: long (nullable = true)
 |-- gasto_com_carnes_2ultimos_anos: long (nullable = true)
 |-- gasto_com_peixes_2ultimos_anos: long (nullable = true)
 |-- gasto_com_doces_2ultimos_anos: long (nullable = true)
 |-- gasto_com_ouro_2ultimos_anos: long (nullable = true)
 |-- qtd_descontos_feitos: long (nullable = true)
 |-- compras_pela_internet: long (nullable = true)
 |-- compras_usando_catalago: long (nullable = true)
 |-- compras_feitas_lojaFisica: long (nullable = true)
 |-- visitantes_site_mensal: long (nullable = true)
 |-- reclamacao_2anos: long (nullable = true)

In [ ]:
# CONSTRUÇÃO DO MEU STRUCT TYPE

schema = StructType([
		StructField('ano_nascimento', IntegerType(), True),
		StructField('escolaridade', StringType(), True),
		StructField('estado_civil', StringType(), True),
    StructField('renda_anual', IntegerType(), True),
    StructField('num_criancas_casa', IntegerType(), True),
    StructField('num_adolescentes_casa', IntegerType(), True),
    StructField('cliente_desde', StringType(), True),
    StructField('dias_ultima_compra', IntegerType(), True),
    StructField('gasto_com_vinho_2ultimos_anos', IntegerType(), True),
    StructField('gasto_com_frutas_2ultimos_anos', IntegerType(), True),
    StructField('gasto_com_carnes_2ultimos_anos', IntegerType(), True),
    StructField('gasto_com_peixes_2ultimos_anos', IntegerType(), True),
    StructField('gasto_com_doces_2ultimos_anos', IntegerType(), True),
    StructField('gasto_com_ouro_2ultimos_anos', IntegerType(), True),
    StructField('qtd_descontos_feitos', IntegerType(), True),
    StructField('compras_pela_internet', IntegerType(), True),
    StructField('compras_usando_catalago', IntegerType(), True),
    StructField('compras_feitas_lojaFisica', IntegerType(), True),
    StructField('visitantes_site_mensal', IntegerType(), True),
    StructField('reclamacao_2anos', IntegerType(), True)
]
)

In [ ]:
# DECIDI RENOMEAR 7 COLUNAS POR OUTRO NOME COM MAIS SENTIDO A COLUNA, PRA ISSO
# CRIEI OUTRO DATAFRAE COM AS COLUNAS RENOMEADAS
df3 = df3.withColumnRenamed('gasto_com_vinho_2ultimos_anos', 'Compra_vinho_2anos')
df3 = df3.withColumnRenamed('gasto_com_frutas_2ultimos_anos', 'Compra_frutas_2anos')
df3 = df3.withColumnRenamed('gasto_com_carnes_2ultimos_anos', 'Compra_carnes_2anos')
df3 = df3.withColumnRenamed('gasto_com_peixes_2ultimos_anos', 'Compra_peixes_2anos')
df3 = df3.withColumnRenamed('gasto_com_doces_2ultimos_anos', 'Compra_doces_2anos')
df3 = df3.withColumnRenamed('gasto_com_ouro_2ultimos_anos', 'Compra_ouro_2anos')
df3 = df3.withColumnRenamed('reclamacao_2anos', 'Reclamou_de_algo')

df3.show()

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|Compra_vinho_2anos|Compra_frutas_2anos|Compra_carnes_2anos|Compra_peixes_2anos|Compra_doces_2anos|Compra_ouro_2anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|Reclamou_de_algo|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+
|         5524|          1957|    Bacharel|  Solteira(o)|    58138.0|                0|                    0|   04-09-2012|                58|               635|                 88|                546|                172|                88|               88|                   3|                    8|                     10|                        4|                     7|               0|
|         2174|          1954|    Bacharel|  Solteira(o)|    46344.0|                1|                    1|   08-03-2014|                38|                11|                  1|                  6|                  2|                 1|                6|                   2|                    1|                      1|                        2|                     5|               0|
|         4141|          1965|    Bacharel|Uniao_Estavel|    71613.0|                0|                    0|   21-08-2013|                26|               426|                 49|                127|                111|                21|               42|                   1|                    8|                      2|                       10|                     4|               0|
|         6182|          1984|    Bacharel|Uniao_Estavel|    26646.0|                1|                    0|   10-02-2014|                26|                11|                  4|                 20|                 10|                 3|                5|                   2|                    2|                      0|                        4|                     6|               0|
|         5324|          1981|   Doutorado|    Casado(a)|    58293.0|                1|                    0|   19-01-2014|                94|               173|                 43|                118|                 46|                27|               15|                   5|                    5|                      3|                        6|                     5|               0|
|         7446|          1967|    Mestrado|Uniao_Estavel|    62513.0|                0|                    1|   09-09-2013|                16|               520|                 42|                 98|                  0|                42|               14|                   2|                    6|                      4|                       10|                     6|               0|
|          965|          1971|    Bacharel|Divorciada(o)|    55635.0|                0|                    1|   13-11-2012|                34|               235|                 65|                164|                 50|                49|               27|                   4|                    7|                      3|                        7|                     6|               0|
|         6177|          1985|   Doutorado|    Casado(a)|    33454.0|                1|                    0|   08-05-2013|                32|                76|                 10|                 56|                  3|                 1|               23|                   2|                    4|                      0|                        4|                     8|               0|
|         4855|          1974|   Doutorado|Uniao_Estavel|    30351.0|                1|                    0|   06-06-2013|                19|                14|                  0|                 24|                  3|                 3|                2|                   1|                    3|                      0|                        2|                     9|               0|
|         5899|          1950|   Doutorado|Uniao_Estavel|     5648.0|                1|                    1|   13-03-2014|                68|                28|                  0|                  6|                  1|                 1|               13|                   1|                    1|                      0|                        0|                    20|               0|
|          387|          1976| Fundamental|    Casado(a)|     7500.0|                0|                    0|   13-11-2012|                59|                 6|                 16|                 11|                 11|                 1|               16|                   1|                    2|                      0|                        3|                     8|               0|
|         2125|          1959|    Bacharel|Divorciada(o)|    63033.0|                0|                    0|   15-11-2013|                82|               194|                 61|                480|                225|               112|               30|                   1|                    3|                      4|                        8|                     2|               0|
|         8180|          1952|    Mestrado|Divorciada(o)|    59354.0|                1|                    1|   15-11-2013|                53|               233|                  2|                 53|                  3|                 5|               14|                   3|                    6|                      1|                        5|                     6|               0|
|         2569|          1987|    Bacharel|    Casado(a)|    17323.0|                0|                    0|   10-10-2012|                38|                 3|                 14|                 17|                  6|                 1|                5|                   1|                    1|                      0|                        3|                     8|               0|
|         2114|          1946|   Doutorado|  Solteira(o)|    82800.0|                0|                    0|   24-11-2012|                23|              1006|                 22|                115|                 59|                68|               45|                   1|                    7|                      6|                       12|                     3|               0|
|         9736|          1980|    Bacharel|    Casado(a)|    41850.0|                1|                    1|   24-12-2012|                51|                53|                  5|                 19|                  2|                13|                4|                   3|                    3|                      0|                        3|                     8|               0|
|         4939|          1946|    Bacharel|Uniao_Estavel|    37760.0|                0|                    0|   31-08-2012|                20|                84|                  5|                 38|                150|                12|               28|                   2|                    4|                      1|                        6|                     7|               0|
|         6565|          1949|    Mestrado|    Casado(a)|    76995.0|                0|                    1|   28-03-2013|                91|              1012|                 80|                498|                  0|                16|              176|                   2|                   11|                      4|                        9|                     5|               0|
|         2278|          1985|Pos-graduado|  Solteira(o)|    33812.0|                1|                    0|   03-11-2012|                86|                 4|                 17|                 19|                 30|                24|               39|                   2|                    2|                      1|                        3|                     6|               0|
|         9360|          1982|    Bacharel|    Casado(a)|    37040.0|                0|                    0|   08-08-2012|                41|                86|                  2|                 73|                 69|                38|               48|                   1|                    4|                      2|                        5|                     8|               0|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+
only showing top 20 rows

CRIAÇÃO DE COLUNAS

In [ ]:
# VOU CRIAR UMA COLUNA DE IDADE PRA SABER ALGUNS DADOS REFERENTES A IDADES DOS CLIENTES

df3 = df3.withColumn("idade", 2022 - F.col("ano_nascimento"))

In [ ]:
# UMA COLUNA COM O SOMATÓRIO DE CRIANÇAS E ADOLESCENTES PRA SABER A QUANTIDADE DE FILHOS

df3 = df3.withColumn('n_Filhos', F.col('num_criancas_casa') + F.col('num_adolescentes_casa'))

In [ ]:
# UMA COLUNA COM O TOTAL DE COMPRAS REALIZADAS
df3 = df3.withColumn('Total_compras', F.col('Compra_vinho_2anos') + F.col('Compra_frutas_2anos') + F.col('Compra_carnes_2anos') + F.col('Compra_peixes_2anos') + F.col('Compra_doces_2anos') + F.col('Compra_ouro_2anos'))

In [ ]:
# UMA COLUNA COM O SOMATÓRIO DE VENDAS REALIZADAS PARA VER A PORCENTAGEM DE COMPRAS FEITAS EM CADA TIPO (INTERNET, LOJA, CATALAGO)
df3 = df3.withColumn('Total_vendas', F.col('compras_pela_internet') + F.col('compras_usando_catalago') + F.col('compras_feitas_lojaFisica'))

In [ ]:
df3.show()

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|Compra_vinho_2anos|Compra_frutas_2anos|Compra_carnes_2anos|Compra_peixes_2anos|Compra_doces_2anos|Compra_ouro_2anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|Reclamou_de_algo|idade|n_Filhos|Total_compras|Total_vendas|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+
|         5524|          1957|    Bacharel|  Solteira(o)|    58138.0|                0|                    0|   04-09-2012|                58|               635|                 88|                546|                172|                88|               88|                   3|                    8|                     10|                        4|                     7|               0|   65|       0|         1617|          22|
|         2174|          1954|    Bacharel|  Solteira(o)|    46344.0|                1|                    1|   08-03-2014|                38|                11|                  1|                  6|                  2|                 1|                6|                   2|                    1|                      1|                        2|                     5|               0|   68|       2|           27|           4|
|         4141|          1965|    Bacharel|Uniao_Estavel|    71613.0|                0|                    0|   21-08-2013|                26|               426|                 49|                127|                111|                21|               42|                   1|                    8|                      2|                       10|                     4|               0|   57|       0|          776|          20|
|         6182|          1984|    Bacharel|Uniao_Estavel|    26646.0|                1|                    0|   10-02-2014|                26|                11|                  4|                 20|                 10|                 3|                5|                   2|                    2|                      0|                        4|                     6|               0|   38|       1|           53|           6|
|         5324|          1981|   Doutorado|    Casado(a)|    58293.0|                1|                    0|   19-01-2014|                94|               173|                 43|                118|                 46|                27|               15|                   5|                    5|                      3|                        6|                     5|               0|   41|       1|          422|          14|
|         7446|          1967|    Mestrado|Uniao_Estavel|    62513.0|                0|                    1|   09-09-2013|                16|               520|                 42|                 98|                  0|                42|               14|                   2|                    6|                      4|                       10|                     6|               0|   55|       1|          716|          20|
|          965|          1971|    Bacharel|Divorciada(o)|    55635.0|                0|                    1|   13-11-2012|                34|               235|                 65|                164|                 50|                49|               27|                   4|                    7|                      3|                        7|                     6|               0|   51|       1|          590|          17|
|         6177|          1985|   Doutorado|    Casado(a)|    33454.0|                1|                    0|   08-05-2013|                32|                76|                 10|                 56|                  3|                 1|               23|                   2|                    4|                      0|                        4|                     8|               0|   37|       1|          169|           8|
|         4855|          1974|   Doutorado|Uniao_Estavel|    30351.0|                1|                    0|   06-06-2013|                19|                14|                  0|                 24|                  3|                 3|                2|                   1|                    3|                      0|                        2|                     9|               0|   48|       1|           46|           5|
|         5899|          1950|   Doutorado|Uniao_Estavel|     5648.0|                1|                    1|   13-03-2014|                68|                28|                  0|                  6|                  1|                 1|               13|                   1|                    1|                      0|                        0|                    20|               0|   72|       2|           49|           1|
|          387|          1976| Fundamental|    Casado(a)|     7500.0|                0|                    0|   13-11-2012|                59|                 6|                 16|                 11|                 11|                 1|               16|                   1|                    2|                      0|                        3|                     8|               0|   46|       0|           61|           5|
|         2125|          1959|    Bacharel|Divorciada(o)|    63033.0|                0|                    0|   15-11-2013|                82|               194|                 61|                480|                225|               112|               30|                   1|                    3|                      4|                        8|                     2|               0|   63|       0|         1102|          15|
|         8180|          1952|    Mestrado|Divorciada(o)|    59354.0|                1|                    1|   15-11-2013|                53|               233|                  2|                 53|                  3|                 5|               14|                   3|                    6|                      1|                        5|                     6|               0|   70|       2|          310|          12|
|         2569|          1987|    Bacharel|    Casado(a)|    17323.0|                0|                    0|   10-10-2012|                38|                 3|                 14|                 17|                  6|                 1|                5|                   1|                    1|                      0|                        3|                     8|               0|   35|       0|           46|           4|
|         2114|          1946|   Doutorado|  Solteira(o)|    82800.0|                0|                    0|   24-11-2012|                23|              1006|                 22|                115|                 59|                68|               45|                   1|                    7|                      6|                       12|                     3|               0|   76|       0|         1315|          25|
|         9736|          1980|    Bacharel|    Casado(a)|    41850.0|                1|                    1|   24-12-2012|                51|                53|                  5|                 19|                  2|                13|                4|                   3|                    3|                      0|                        3|                     8|               0|   42|       2|           96|           6|
|         4939|          1946|    Bacharel|Uniao_Estavel|    37760.0|                0|                    0|   31-08-2012|                20|                84|                  5|                 38|                150|                12|               28|                   2|                    4|                      1|                        6|                     7|               0|   76|       0|          317|          11|
|         6565|          1949|    Mestrado|    Casado(a)|    76995.0|                0|                    1|   28-03-2013|                91|              1012|                 80|                498|                  0|                16|              176|                   2|                   11|                      4|                        9|                     5|               0|   73|       1|         1782|          24|
|         2278|          1985|Pos-graduado|  Solteira(o)|    33812.0|                1|                    0|   03-11-2012|                86|                 4|                 17|                 19|                 30|                24|               39|                   2|                    2|                      1|                        3|                     6|               0|   37|       1|          133|           6|
|         9360|          1982|    Bacharel|    Casado(a)|    37040.0|                0|                    0|   08-08-2012|                41|                86|                  2|                 73|                 69|                38|               48|                   1|                    4|                      2|                        5|                     8|               0|   40|       0|          316|          11|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+
only showing top 20 rows

INSIGHTS E AGRUPAMENTOS

In [ ]:
# QUAL NÍVEL DE ESCOLARIDADE POSSUI MAIOR NUMERO DE FILHOS E QUAL COMPRAM MAIS?
df3.groupBy(F.col("escolaridade")).sum("n_Filhos", "Total_compras").show()


'''
Podemos ver que pessoas com pelo menos o nível Bacharel tem mais filhos, enquanto
que o nivel educacional fundamental apresenta um numero de filhos muito menor.
O mesmo se observa na quantidade de itens comprados em 2 itens, pessoas com Bacharel
ja fizeram quase 700 mil compras, enquanto pessoas de nivem mais basico não chegou nem a 
4500 compras realizadas durante 2 anos
'''

+------------+-------------+------------------+
|escolaridade|sum(n_Filhos)|sum(Total_compras)|
+------------+-------------+------------------+
|Pos-graduado|          177|             98986|
|   Doutorado|          480|            325509|
| Fundamental|           39|              4417|
|    Bacharel|         1041|            693802|
|    Mestrado|          362|            222565|
+------------+-------------+------------------+

'\nPodemos ver que pessoas com pelo menos o nível Bacharel tem mais filhos, enquanto\nque o nivel educacional fundamental apresenta um numero de filhos muito menor.\nO mesmo se observa na quantidade de itens comprados em 2 itens, pessoas com Bacharel\nja fizeram quase 700 mil compras, enquanto pessoas de nivem mais basico não chegou nem a \n4500 compras realizadas durante 2 anos\n'

In [ ]:
# QUAL ESTADO CIVIL FEZ MAIS RECLAMAÇÕES NOS ULTIMOS 2 ANOS?

df3.groupBy(F.col("estado_civil")).sum("Reclamou_de_algo").show()

'''
Como apresenta a tabela, gente casada fazem mais reclamações do que outros
estados relacionais.
Puxar a atenção para os estados civís Sozinho, Assexuados, Viuvos e Livres,
que não prestaram nenhuma reclamação no mesmo periodo
'''

+-------------+---------------------+
| estado_civil|sum(Reclamou_de_algo)|
+-------------+---------------------+
|  Solteira(o)|                    6|
|    Casado(a)|                    8|
|   Sozinho(a)|                    0|
|Uniao_Estavel|                    5|
|    Assexuada|                    0|
|Divorciada(o)|                    2|
|     viuvo(a)|                    0|
|        Livre|                    0|
+-------------+---------------------+

'\nComo apresenta a tabela, gente casada fazem mais reclamações do que outros\nestados relacionais.\nPuxar a atenção para os estados civís Sozinho, Assexuados, Viuvos e Livres,\nque não prestaram nenhuma reclamação no mesmo periodo\n'

In [ ]:
# QUEM SÃO OS IDOSOS SEM FILHOS DESSA TABELA?
df3.filter((F.col("idade") >=70) & (F.col("n_Filhos") == 0)).show(50)

'''
Pelo que se vê nas 50 primeiras linhas, a maioria possui doutorado ou mestrado,
são casadas ou estão em união estável e  compram muito mais vinho do que carne, peixes, doces e ouro.

'''

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|Compra_vinho_2anos|Compra_frutas_2anos|Compra_carnes_2anos|Compra_peixes_2anos|Compra_doces_2anos|Compra_ouro_2anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|Reclamou_de_algo|idade|n_Filhos|Total_compras|Total_vendas|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+
|         2114|          1946|   Doutorado|  Solteira(o)|    82800.0|                0|                    0|   24-11-2012|                23|              1006|                 22|                115|                 59|                68|               45|                   1|                    7|                      6|                       12|                     3|               0|   76|       0|         1315|          25|
|         4939|          1946|    Bacharel|Uniao_Estavel|    37760.0|                0|                    0|   31-08-2012|                20|                84|                  5|                 38|                150|                12|               28|                   2|                    4|                      1|                        6|                     7|               0|   76|       0|          317|          11|
|         8755|          1946|    Mestrado|    Casado(a)|    68657.0|                0|                    0|   20-02-2013|                 4|               482|                 34|                471|                119|                68|               22|                   1|                    3|                      5|                        9|                     7|               0|   76|       0|         1196|          17|
|         2968|          1943|   Doutorado|Divorciada(o)|    48948.0|                0|                    0|   01-02-2013|                53|               437|                  8|                206|                160|                49|               42|                   2|                    7|                     10|                        5|                     6|               0|   79|       0|          902|          22|
|         4137|          1948|    Bacharel|Uniao_Estavel|    70666.0|                0|                    0|   06-12-2013|                29|               398|                 40|                367|                119|               122|               30|                   1|                    7|                      4|                        4|                     4|               0|   74|       0|         1076|          15|
|         1050|          1952|    Bacharel|    Casado(a)|    28332.0|                0|                    0|   30-04-2014|                58|                14|                 10|                 13|                  4|                15|                9|                   1|                    2|                      1|                        4|                     2|               0|   70|       0|           65|           7|
|         4646|          1951|Pos-graduado|    Casado(a)|    78497.0|                0|                    0|   01-12-2013|                44|               207|                 26|                447|                 75|                 0|              223|                   1|                    5|                      7|                       12|                     2|               0|   71|       0|          978|          24|
|         9370|          1945|   Doutorado|    Casado(a)|    65846.0|                0|                    0|   17-05-2013|                68|               562|                 81|                276|                 80|                40|               81|                   1|                    6|                      3|                        6|                     4|               0|   77|       0|         1120|          15|
|        10240|          1949|    Bacharel|Uniao_Estavel|    69372.0|                0|                    0|   19-02-2013|                10|               997|                 26|                269|                 34|                13|               42|                   1|                   10|                      4|                        6|                     4|               0|   73|       0|         1381|          20|
|         9260|          1945|   Doutorado|    Casado(a)|    70356.0|                0|                    0|   05-11-2012|                20|              1349|                 16|                249|                 43|                16|               33|                   2|                   10|                      6|                        9|                     6|               0|   77|       0|         1706|          25|
|        10314|          1948|   Doutorado|    Casado(a)|    83837.0|                0|                    0|   16-12-2012|                79|               847|                 66|                119|                 86|                89|              111|                   1|                    9|                     10|                        5|                     4|               0|   74|       0|         1318|          24|
|         6935|          1951|Pos-graduado|    Casado(a)|    78497.0|                0|                    0|   01-12-2013|                44|               207|                 26|                447|                 75|                 0|              223|                   1|                    5|                      7|                       12|                     2|               0|   71|       0|          978|          24|
|        10562|          1946|    Mestrado|    Casado(a)|    66835.0|                0|                    0|   28-09-2013|                21|               620|                 26|                195|                 34|                17|              141|                   1|                    6|                      4|                       13|                     2|               0|   76|       0|         1033|          23|
|         6274|          1948|    Mestrado|    Casado(a)|    83790.0|                0|                    0|   15-11-2013|                81|              1076|                 16|                417|                 42|                48|               16|                   1|                    8|                     10|                        6|                     3|               0|   74|       0|         1615|          24|
|         9617|          1951|    Bacharel|  Solteira(o)|    15033.0|                0|                    0|   16-04-2014|                37|                 0|                  4|                  5|                  6|                 0|                4|                   1|                    1|                      0|                        3|                     3|               0|   71|       0|           19|           4|
|         8652|          1946|    Bacharel|Uniao_Estavel|    37760.0|                0|                    0|   31-08-2012|                20|                84|                  5|                 38|                150|                12|               28|                   2|                    4|                      1|                        6|                     7|               0|   76|       0|          317|          11|
|        10983|          1952|    Bacharel|Uniao_Estavel|    75278.0|                0|                    0|   29-01-2013|                17|               304|                 98|                230|                150|                74|               74|                   1|                    6|                      3|                       13|                     3|               0|   70|       0|          930|          22|
|         4697|          1949|    Mestrado|Divorciada(o)|    35416.0|                0|                    0|   13-06-2013|                62|               248|                  3|                 81|                  4|                 3|               51|                   3|                    7|                      1|                        5|                     8|               0|   73|       0|          390|          13|
|         6963|          1947|    Bacharel|  Solteira(o)|    77457.0|                0|                    0|   05-03-2014|                85|               675|                 11|                400|                 15|                45|               11|                   1|                    2|                      5|                       10|                     1|               0|   75|       0|         1157|          17|
|         1150|          1899|   Doutorado|Uniao_Estavel|    83532.0|                0|                    0|   26-09-2013|                36|               755|                144|                562|                104|                64|              224|                   1|                    4|                      6|                        4|                     1|               0|  123|       0|         1853|          14|
|         1411|          1952|    Bacharel|Divorciada(o)|    82623.0|                0|                    0|   10-11-2013|                58|               204|                 34|                204|                172|               153|              173|                   1|                    2|                      9|                        4|                     1|               0|   70|       0|          940|          15|
|         6142|          1943|    Mestrado|    Casado(a)|    65073.0|                0|                    0|   20-08-2013|                65|               629|                 17|                177|                 69|                 0|                8|                   1|                    5|                      3|                        5|                     2|               1|   79|       0|          900|          13|
|          455|          1946|   Doutorado|    Casado(a)|    51012.0|                0|                    0|   18-04-2013|                86|               102|                  9|                 63|                  2|                 9|               24|                   1|                    4|                      1|                        4|                     6|               0|   76|       0|          209|           9|
|         7106|          1943|   Doutorado|    Casado(a)|    75865.0|                0|                    0|   31-03-2014|                73|               483|                  0|                591|                156|                 0|               12|                   1|                    3|                      5|                       10|                     1|               0|   79|       0|         1242|          18|
|         6932|          1941|   Doutorado|    Casado(a)|    93027.0|                0|                    0|   13-04-2013|                77|              1285|                 42|                716|                 55|                 0|               21|                   0|                    7|                     10|                        5|                     2|               0|   81|       0|         2119|          22|
|         5029|          1946|    Bacharel|    Casado(a)|    18100.0|                0|                    0|   06-08-2013|                14|                 3|                  1|                  2|                  4|                 3|                1|                   1|                    0|                      0|                        3|                     5|               0|   76|       0|           14|           3|
|         7851|          1949|    Bacharel|     viuvo(a)|    70165.0|                0|                    0|   22-09-2013|                60|               161|                  0|                253|                199|               191|              122|                   1|                    3|                      7|                       11|                     1|               0|   73|       0|          926|          21|
|         3921|          1952|Pos-graduado|     viuvo(a)|    28457.0|                0|                    0|   28-10-2012|                96|                24|                  1|                108|                 29|                29|               14|                   1|                    4|                      1|                        4|                     8|               0|   70|       0|          205|           9|
|         6605|          1944|   Doutorado|Divorciada(o)|    55614.0|                0|                    0|   27-11-2013|                85|               504|                 13|                131|                  8|                 0|               26|                   1|                    9|                      4|                        6|                     7|               0|   78|       0|          682|          19|
|          466|          1944|    Bacharel|    Casado(a)|    65275.0|                0|                    0|   03-04-2013|                 9|               388|                 14|                218|                 91|                14|               21|                   1|                    4|                      3|                       13|                     2|               0|   78|       0|          746|          20|
|         3711|          1944|    Mestrado|    Casado(a)|    80184.0|                0|                    0|   01-03-2014|                19|              1035|                134|                670|                 25|                38|                0|                   1|                    6|                      3|                       10|                     3|               0|   78|       0|         1902|          19|
|         9504|          1949|    Mestrado|    Casado(a)|    81698.0|                0|                    0|   06-11-2013|                 4|               179|                 28|                520|                111|               123|               47|                   1|                    3|                      8|                       13|                     1|               0|   73|       0|         1008|          24|
|         5123|          1951|    Mestrado|    Casado(a)|    27450.0|                0|                    0|   15-04-2013|                57|                37|                 12|                 23|                  8|                11|               52|                   1|                    2|                      1|                        3|                     7|               0|   71|       0|          143|           6|
|         4587|          1944|    Mestrado|     viuvo(a)|    45006.0|                0|                    0|   18-07-2013|                90|               162|                 25|                 53|                 16|                 0|               10|                   1|                    3|                      1|                        7|                     3|               0|   78|       0|          266|          11|
|        10972|          1949|    Bacharel|     viuvo(a)|    72298.0|                0|                    0|   10-03-2014|                52|               625|                 35|                169|                 58|                17|               35|                   1|                    4|                      3|                        6|                     1|               0|   73|       0|          939|          13|
|         6945|          1952|    Bacharel|  Solteira(o)|    84574.0|                0|                    0|   04-06-2013|                72|               387|                 20|                713|                 38|                54|              163|                   1|                    9|                     11|                       11|                     5|               0|   70|       0|         1375|          31|
|         4149|          1948|   Doutorado|Uniao_Estavel|    76140.0|                0|                    0|   13-05-2014|                57|               586|                 66|                653|                 17|                 0|               26|                   1|                    5|                      9|                        6|                     2|               0|   74|       0|         1348|          20|
|         1173|          1947|    Mestrado|Uniao_Estavel|    77632.0|                0|                    0|   10-03-2013|                73|              1200|                105|                758|                  0|                42|              147|                   1|                    4|                      2|                        6|                     2|               0|   75|       0|         2252|          12|
|         9316|          1952| Fundamental|Uniao_Estavel|    13084.0|                0|                    0|   02-11-2013|                29|                 2|                  0|                  7|                  3|                 7|               10|                   1|                    1|                      0|                        3|                     6|               0|   70|       0|           29|           4|
|         7875|          1949|    Bacharel|    Casado(a)|    72025.0|                0|                    0|   29-04-2014|                46|               967|                  0|                617|                 43|                50|                0|                   1|                    4|                      8|                       13|                     2|               0|   73|       0|         1677|          25|
|         3560|          1952|    Bacharel|Uniao_Estavel|    83844.0|                0|                    0|   12-05-2013|                57|               901|                 31|                345|                 75|                31|              191|                   1|                    4|                      4|                       11|                     1|               0|   70|       0|         1574|          19|
|         4508|          1952|    Bacharel|  Solteira(o)|    75127.0|                0|                    0|   22-05-2014|                92|               203|                 35|                305|                 46|                17|              227|                   1|                    2|                     11|                        5|                     1|               0|   70|       0|          833|          18|
|         1915|          1951|   Doutorado|    Casado(a)|    78939.0|                0|                    0|   12-12-2013|                57|               794|                115|                243|                150|                 0|              205|                   1|                    8|                      5|                        6|                     3|               0|   71|       0|         1507|          19|

'\nPelo que se vê nas 50 primeiras linhas, a maioria possui doutorado ou mestrado,\nsão casadas ou estão em união estável e  compram muito mais vinho do que carne, peixes, doces e ouro.\n\n'

In [ ]:
# QUAL GRUPO DE ESCOLARIDADE COMPRAm MAIS COM DESCONTO?

df3.groupBy(F.col("escolaridade")).sum("Total_compras", "qtd_descontos_feitos").show()

'''
Mais uma vez podemos perceber que o grupo Bacharel se destaca mais, sendo 
a escolaridade que mais compram com desconto.
'''

+------------+------------------+-------------------------+
|escolaridade|sum(Total_compras)|sum(qtd_descontos_feitos)|
+------------+------------------+-------------------------+
|Pos-graduado|             98986|                      452|
|   Doutorado|            325509|                     1135|
| Fundamental|              4417|                       97|
|    Bacharel|            693802|                     2580|
|    Mestrado|            222565|                      885|
+------------+------------------+-------------------------+

'\nMais uma vez podemos perceber que o grupo Bacharel se destaca mais, sendo \na escolaridade que mais compram com desconto.\n'

WINDOW FUNCTIONS

In [ ]:
# VOU CRIAR UMA WINDOW FUNCTION COM BASE NO TOTAL DE VENDAS PARA CADA GRAU DE ESCOLARIDADE

windowFunc  = Window.partitionBy("escolaridade").orderBy("Total_vendas")

In [ ]:
# ROW NUMBER PRA VIR UMA CLASSIFICAÇÃO DO PRIMEIRO AO ULTIMO SEPARADO PELOS GRUPOS

df3.withColumn("row_number", F.row_number().over(windowFunc)).show()

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+----------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|Compra_vinho_2anos|Compra_frutas_2anos|Compra_carnes_2anos|Compra_peixes_2anos|Compra_doces_2anos|Compra_ouro_2anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|Reclamou_de_algo|idade|n_Filhos|Total_compras|Total_vendas|row_number|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+----------+
|         5555|          1975|    Bacharel|Divorciada(o)|   153924.0|                0|                    0|   07-02-2014|                81|                 1|                  1|                  1|                  1|                 1|                1|                   0|                    0|                      0|                        0|                     0|               0|   47|       0|            6|           0|         1|
|         3955|          1965|    Bacharel|Divorciada(o)|     4861.0|                0|                    0|   22-06-2014|                20|                 2|                  1|                  1|                  1|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   57|       0|            6|           0|         2|
|         6862|          1971|    Bacharel|Divorciada(o)|     1730.0|                0|                    0|   18-05-2014|                65|                 1|                  1|                  3|                  1|                 1|                1|                  15|                    0|                      0|                        0|                    20|               0|   51|       0|            8|           0|         3|
|        11110|          1973|    Bacharel|  Solteira(o)|     3502.0|                1|                    0|   13-04-2013|                56|                 2|                  1|                  1|                  0|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   49|       1|            5|           0|         4|
|        10749|          1991|    Bacharel|  Solteira(o)|     8028.0|                0|                    0|   18-09-2012|                62|                73|                 18|                 66|                  7|                12|                2|                  15|                    0|                      1|                        0|                    19|               0|   31|       0|          178|           1|         5|
|         9303|          1976|    Bacharel|    Casado(a)|     5305.0|                0|                    1|   30-07-2013|                12|                12|                  4|                  7|                  1|                 3|                5|                   0|                    1|                      0|                        0|                    13|               0|   46|       1|           32|           1|         6|
|         8430|          1957|    Bacharel|Uniao_Estavel|    21994.0|                0|                    1|   24-12-2012|                 4|                 9|                  0|                  6|                  3|                 1|                3|                   1|                    0|                      0|                        3|                     5|               0|   65|       1|           22|           3|         7|
|         1386|          1967|    Bacharel|Uniao_Estavel|    32474.0|                1|                    1|   11-05-2014|                 0|                10|                  0|                  1|                  0|                 0|                0|                   1|                    1|                      0|                        2|                     7|               0|   55|       2|           11|           3|         8|
|         5846|          1977|    Bacharel|Divorciada(o)|    40246.0|                1|                    0|   19-12-2012|                68|                 2|                  1|                  6|                  2|                 1|                1|                   1|                    1|                      0|                        2|                     6|               0|   45|       1|           13|           3|         9|
|         2261|          1969|    Bacharel|    Casado(a)|    26304.0|                1|                    0|   23-06-2013|                 5|                 4|                  1|                  5|                  2|                 0|                4|                   1|                    1|                      0|                        2|                     7|               0|   53|       1|           16|           3|        10|
|         3120|          1981|    Bacharel|Uniao_Estavel|    38547.0|                1|                    0|   28-08-2013|                49|                 6|                  1|                 10|                  0|                 1|                4|                   1|                    1|                      0|                        2|                     8|               1|   41|       1|           22|           3|        11|
|         9283|          1978|    Bacharel|  Solteira(o)|    60199.0|                1|                    2|   12-09-2013|                49|                 8|                  1|                  7|                  2|                 0|                0|                   1|                    0|                      0|                        3|                     4|               0|   44|       3|           18|           3|        12|
|        10492|          1959|    Bacharel|Uniao_Estavel|    38285.0|                2|                    1|   24-06-2014|                96|                 2|                  0|                  5|                  2|                 0|                1|                   1|                    0|                      0|                        3|                     2|               0|   63|       3|           10|           3|        13|
|         1606|          1971|    Bacharel|Uniao_Estavel|    38590.0|                1|                    0|   15-05-2013|                65|                 3|                  1|                  8|                  4|                 3|                3|                   1|                    1|                      0|                        2|                     8|               0|   51|       1|           22|           3|        14|
|        10451|          1965|    Bacharel|Uniao_Estavel|    29672.0|                1|                    1|   12-03-2013|                 6|                 9|                  1|                  3|                  0|                 4|                8|                   1|                    0|                      0|                        3|                     6|               0|   57|       2|           25|           3|        15|
|          520|          1974|    Bacharel|    Casado(a)|    34421.0|                1|                    0|   01-07-2013|                81|                 3|                  3|                  7|                  6|                 2|                9|                   1|                    1|                      0|                        2|                     7|               0|   48|       1|           30|           3|        16|
|         2861|          1983|    Bacharel|  Solteira(o)|    24072.0|                1|                    0|   16-04-2013|                79|                 9|                  1|                  6|                  3|                 0|                4|                   1|                    1|                      0|                        2|                     8|               0|   39|       1|           23|           3|        17|
|         9543|          1985|    Bacharel|    Casado(a)|    19986.0|                1|                    0|   14-11-2013|                74|                 3|                  6|                  5|                  0|                 2|                6|                   1|                    0|                      0|                        3|                     7|               0|   37|       1|           22|           3|        18|
|         7284|          1953|    Bacharel|    Casado(a)|    48686.0|                1|                    2|   04-12-2013|                 8|                10|                  0|                  7|                  2|                 0|                1|                   1|                    1|                      0|                        2|                     8|               0|   69|       3|           20|           3|        19|
|         5029|          1946|    Bacharel|    Casado(a)|    18100.0|                0|                    0|   06-08-2013|                14|                 3|                  1|                  2|                  4|                 3|                1|                   1|                    0|                      0|                        3|                     5|               0|   76|       0|           14|           3|        20|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+----------+
only showing top 20 rows

In [ ]:
# NESTA WINDOW FUNCTION, ESTOU TRAZENDO A IDADE MÉDIA DO GRUPO

df3 = df3.withColumn("media", avg(F.col("idade")).over(windowFunc))
df3.show()

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|Compra_vinho_2anos|Compra_frutas_2anos|Compra_carnes_2anos|Compra_peixes_2anos|Compra_doces_2anos|Compra_ouro_2anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|Reclamou_de_algo|idade|n_Filhos|Total_compras|Total_vendas|             media|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
|         5555|          1975|    Bacharel|Divorciada(o)|   153924.0|                0|                    0|   07-02-2014|                81|                 1|                  1|                  1|                  1|                 1|                1|                   0|                    0|                      0|                        0|                     0|               0|   47|       0|            6|           0|              51.0|
|         3955|          1965|    Bacharel|Divorciada(o)|     4861.0|                0|                    0|   22-06-2014|                20|                 2|                  1|                  1|                  1|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   57|       0|            6|           0|              51.0|
|         6862|          1971|    Bacharel|Divorciada(o)|     1730.0|                0|                    0|   18-05-2014|                65|                 1|                  1|                  3|                  1|                 1|                1|                  15|                    0|                      0|                        0|                    20|               0|   51|       0|            8|           0|              51.0|
|        11110|          1973|    Bacharel|  Solteira(o)|     3502.0|                1|                    0|   13-04-2013|                56|                 2|                  1|                  1|                  0|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   49|       1|            5|           0|              51.0|
|        10749|          1991|    Bacharel|  Solteira(o)|     8028.0|                0|                    0|   18-09-2012|                62|                73|                 18|                 66|                  7|                12|                2|                  15|                    0|                      1|                        0|                    19|               0|   31|       0|          178|           1|46.833333333333336|
|         9303|          1976|    Bacharel|    Casado(a)|     5305.0|                0|                    1|   30-07-2013|                12|                12|                  4|                  7|                  1|                 3|                5|                   0|                    1|                      0|                        0|                    13|               0|   46|       1|           32|           1|46.833333333333336|
|         8430|          1957|    Bacharel|Uniao_Estavel|    21994.0|                0|                    1|   24-12-2012|                 4|                 9|                  0|                  6|                  3|                 1|                3|                   1|                    0|                      0|                        3|                     5|               0|   65|       1|           22|           3| 49.57142857142857|
|         1386|          1967|    Bacharel|Uniao_Estavel|    32474.0|                1|                    1|   11-05-2014|                 0|                10|                  0|                  1|                  0|                 0|                0|                   1|                    1|                      0|                        2|                     7|               0|   55|       2|           11|           3| 49.57142857142857|
|         5846|          1977|    Bacharel|Divorciada(o)|    40246.0|                1|                    0|   19-12-2012|                68|                 2|                  1|                  6|                  2|                 1|                1|                   1|                    1|                      0|                        2|                     6|               0|   45|       1|           13|           3| 49.57142857142857|
|         2261|          1969|    Bacharel|    Casado(a)|    26304.0|                1|                    0|   23-06-2013|                 5|                 4|                  1|                  5|                  2|                 0|                4|                   1|                    1|                      0|                        2|                     7|               0|   53|       1|           16|           3| 49.57142857142857|
|         3120|          1981|    Bacharel|Uniao_Estavel|    38547.0|                1|                    0|   28-08-2013|                49|                 6|                  1|                 10|                  0|                 1|                4|                   1|                    1|                      0|                        2|                     8|               1|   41|       1|           22|           3| 49.57142857142857|
|         9283|          1978|    Bacharel|  Solteira(o)|    60199.0|                1|                    2|   12-09-2013|                49|                 8|                  1|                  7|                  2|                 0|                0|                   1|                    0|                      0|                        3|                     4|               0|   44|       3|           18|           3| 49.57142857142857|
|        10492|          1959|    Bacharel|Uniao_Estavel|    38285.0|                2|                    1|   24-06-2014|                96|                 2|                  0|                  5|                  2|                 0|                1|                   1|                    0|                      0|                        3|                     2|               0|   63|       3|           10|           3| 49.57142857142857|
|         1606|          1971|    Bacharel|Uniao_Estavel|    38590.0|                1|                    0|   15-05-2013|                65|                 3|                  1|                  8|                  4|                 3|                3|                   1|                    1|                      0|                        2|                     8|               0|   51|       1|           22|           3| 49.57142857142857|
|        10451|          1965|    Bacharel|Uniao_Estavel|    29672.0|                1|                    1|   12-03-2013|                 6|                 9|                  1|                  3|                  0|                 4|                8|                   1|                    0|                      0|                        3|                     6|               0|   57|       2|           25|           3| 49.57142857142857|
|          520|          1974|    Bacharel|    Casado(a)|    34421.0|                1|                    0|   01-07-2013|                81|                 3|                  3|                  7|                  6|                 2|                9|                   1|                    1|                      0|                        2|                     7|               0|   48|       1|           30|           3| 49.57142857142857|
|         2861|          1983|    Bacharel|  Solteira(o)|    24072.0|                1|                    0|   16-04-2013|                79|                 9|                  1|                  6|                  3|                 0|                4|                   1|                    1|                      0|                        2|                     8|               0|   39|       1|           23|           3| 49.57142857142857|
|         9543|          1985|    Bacharel|    Casado(a)|    19986.0|                1|                    0|   14-11-2013|                74|                 3|                  6|                  5|                  0|                 2|                6|                   1|                    0|                      0|                        3|                     7|               0|   37|       1|           22|           3| 49.57142857142857|
|         7284|          1953|    Bacharel|    Casado(a)|    48686.0|                1|                    2|   04-12-2013|                 8|                10|                  0|                  7|                  2|                 0|                1|                   1|                    1|                      0|                        2|                     8|               0|   69|       3|           20|           3| 49.57142857142857|
|         5029|          1946|    Bacharel|    Casado(a)|    18100.0|                0|                    0|   06-08-2013|                14|                 3|                  1|                  2|                  4|                 3|                1|                   1|                    0|                      0|                        3|                     5|               0|   76|       0|           14|           3| 49.57142857142857|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
only showing top 20 rows

In [ ]:
df3.printSchema()

root
 |-- identificacao: long (nullable = true)
 |-- ano_nascimento: long (nullable = true)
 |-- escolaridade: string (nullable = true)
 |-- estado_civil: string (nullable = true)
 |-- renda_anual: double (nullable = true)
 |-- num_criancas_casa: long (nullable = true)
 |-- num_adolescentes_casa: long (nullable = true)
 |-- cliente_desde: string (nullable = true)
 |-- dias_ultima_compra: long (nullable = true)
 |-- Compra_vinho_2anos: long (nullable = true)
 |-- Compra_frutas_2anos: long (nullable = true)
 |-- Compra_carnes_2anos: long (nullable = true)
 |-- Compra_peixes_2anos: long (nullable = true)
 |-- Compra_doces_2anos: long (nullable = true)
 |-- Compra_ouro_2anos: long (nullable = true)
 |-- qtd_descontos_feitos: long (nullable = true)
 |-- compras_pela_internet: long (nullable = true)
 |-- compras_usando_catalago: long (nullable = true)
 |-- compras_feitas_lojaFisica: long (nullable = true)
 |-- visitantes_site_mensal: long (nullable = true)
 |-- Reclamou_de_algo: long (nullable = true)
 |-- idade: long (nullable = true)
 |-- n_Filhos: long (nullable = true)
 |-- Total_compras: long (nullable = true)
 |-- Total_vendas: long (nullable = true)
 |-- media: double (nullable = true)

## SPARK SQL

In [ ]:
df3.show()

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|Compra_vinho_2anos|Compra_frutas_2anos|Compra_carnes_2anos|Compra_peixes_2anos|Compra_doces_2anos|Compra_ouro_2anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|Reclamou_de_algo|idade|n_Filhos|Total_compras|Total_vendas|             media|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
|         5555|          1975|    Bacharel|Divorciada(o)|   153924.0|                0|                    0|   07-02-2014|                81|                 1|                  1|                  1|                  1|                 1|                1|                   0|                    0|                      0|                        0|                     0|               0|   47|       0|            6|           0|              51.0|
|         3955|          1965|    Bacharel|Divorciada(o)|     4861.0|                0|                    0|   22-06-2014|                20|                 2|                  1|                  1|                  1|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   57|       0|            6|           0|              51.0|
|         6862|          1971|    Bacharel|Divorciada(o)|     1730.0|                0|                    0|   18-05-2014|                65|                 1|                  1|                  3|                  1|                 1|                1|                  15|                    0|                      0|                        0|                    20|               0|   51|       0|            8|           0|              51.0|
|        11110|          1973|    Bacharel|  Solteira(o)|     3502.0|                1|                    0|   13-04-2013|                56|                 2|                  1|                  1|                  0|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   49|       1|            5|           0|              51.0|
|        10749|          1991|    Bacharel|  Solteira(o)|     8028.0|                0|                    0|   18-09-2012|                62|                73|                 18|                 66|                  7|                12|                2|                  15|                    0|                      1|                        0|                    19|               0|   31|       0|          178|           1|46.833333333333336|
|         9303|          1976|    Bacharel|    Casado(a)|     5305.0|                0|                    1|   30-07-2013|                12|                12|                  4|                  7|                  1|                 3|                5|                   0|                    1|                      0|                        0|                    13|               0|   46|       1|           32|           1|46.833333333333336|
|         8430|          1957|    Bacharel|Uniao_Estavel|    21994.0|                0|                    1|   24-12-2012|                 4|                 9|                  0|                  6|                  3|                 1|                3|                   1|                    0|                      0|                        3|                     5|               0|   65|       1|           22|           3| 49.57142857142857|
|         1386|          1967|    Bacharel|Uniao_Estavel|    32474.0|                1|                    1|   11-05-2014|                 0|                10|                  0|                  1|                  0|                 0|                0|                   1|                    1|                      0|                        2|                     7|               0|   55|       2|           11|           3| 49.57142857142857|
|         5846|          1977|    Bacharel|Divorciada(o)|    40246.0|                1|                    0|   19-12-2012|                68|                 2|                  1|                  6|                  2|                 1|                1|                   1|                    1|                      0|                        2|                     6|               0|   45|       1|           13|           3| 49.57142857142857|
|         2261|          1969|    Bacharel|    Casado(a)|    26304.0|                1|                    0|   23-06-2013|                 5|                 4|                  1|                  5|                  2|                 0|                4|                   1|                    1|                      0|                        2|                     7|               0|   53|       1|           16|           3| 49.57142857142857|
|         3120|          1981|    Bacharel|Uniao_Estavel|    38547.0|                1|                    0|   28-08-2013|                49|                 6|                  1|                 10|                  0|                 1|                4|                   1|                    1|                      0|                        2|                     8|               1|   41|       1|           22|           3| 49.57142857142857|
|         9283|          1978|    Bacharel|  Solteira(o)|    60199.0|                1|                    2|   12-09-2013|                49|                 8|                  1|                  7|                  2|                 0|                0|                   1|                    0|                      0|                        3|                     4|               0|   44|       3|           18|           3| 49.57142857142857|
|        10492|          1959|    Bacharel|Uniao_Estavel|    38285.0|                2|                    1|   24-06-2014|                96|                 2|                  0|                  5|                  2|                 0|                1|                   1|                    0|                      0|                        3|                     2|               0|   63|       3|           10|           3| 49.57142857142857|
|         1606|          1971|    Bacharel|Uniao_Estavel|    38590.0|                1|                    0|   15-05-2013|                65|                 3|                  1|                  8|                  4|                 3|                3|                   1|                    1|                      0|                        2|                     8|               0|   51|       1|           22|           3| 49.57142857142857|
|        10451|          1965|    Bacharel|Uniao_Estavel|    29672.0|                1|                    1|   12-03-2013|                 6|                 9|                  1|                  3|                  0|                 4|                8|                   1|                    0|                      0|                        3|                     6|               0|   57|       2|           25|           3| 49.57142857142857|
|          520|          1974|    Bacharel|    Casado(a)|    34421.0|                1|                    0|   01-07-2013|                81|                 3|                  3|                  7|                  6|                 2|                9|                   1|                    1|                      0|                        2|                     7|               0|   48|       1|           30|           3| 49.57142857142857|
|         2861|          1983|    Bacharel|  Solteira(o)|    24072.0|                1|                    0|   16-04-2013|                79|                 9|                  1|                  6|                  3|                 0|                4|                   1|                    1|                      0|                        2|                     8|               0|   39|       1|           23|           3| 49.57142857142857|
|         9543|          1985|    Bacharel|    Casado(a)|    19986.0|                1|                    0|   14-11-2013|                74|                 3|                  6|                  5|                  0|                 2|                6|                   1|                    0|                      0|                        3|                     7|               0|   37|       1|           22|           3| 49.57142857142857|
|         7284|          1953|    Bacharel|    Casado(a)|    48686.0|                1|                    2|   04-12-2013|                 8|                10|                  0|                  7|                  2|                 0|                1|                   1|                    1|                      0|                        2|                     8|               0|   69|       3|           20|           3| 49.57142857142857|
|         5029|          1946|    Bacharel|    Casado(a)|    18100.0|                0|                    0|   06-08-2013|                14|                 3|                  1|                  2|                  4|                 3|                1|                   1|                    0|                      0|                        3|                     5|               0|   76|       0|           14|           3| 49.57142857142857|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
only showing top 20 rows

In [ ]:
# COMO SÃO OS DADOS DE QUEM ESTA ACIMA DE 70 ANOS E POSSUI BACHAREL?

df3.select(F.col("ano_nascimento"), F.col("estado_civil"), F.col("renda_anual"), F.col("n_Filhos"), F.col("Total_compras"), F.col("Reclamou_de_algo")).where(F.col("escolaridade") == "Bacharel").filter(F.col("idade") > 70).orderBy("ano_nascimento").show()

+--------------+-------------+-----------+--------+-------------+----------------+
|ano_nascimento| estado_civil|renda_anual|n_Filhos|Total_compras|Reclamou_de_algo|
+--------------+-------------+-----------+--------+-------------+----------------+
|          1944|    Casado(a)|    80589.0|       0|         1428|               0|
|          1944|    Casado(a)|    55956.0|       0|          999|               0|
|          1944|    Casado(a)|    65275.0|       0|          746|               0|
|          1945|     viuvo(a)|    63285.0|       0|         1103|               0|
|          1945|    Casado(a)|    69755.0|       0|          894|               0|
|          1946|Uniao_Estavel|    37760.0|       0|          317|               0|
|          1946|Uniao_Estavel|    82657.0|       0|         2283|               0|
|          1946|Uniao_Estavel|    37760.0|       0|          317|               0|
|          1946|    Casado(a)|    78569.0|       0|         1736|               0|
|          1946|    Casado(a)|    18100.0|       0|           14|               0|
|          1947|  Solteira(o)|    77457.0|       0|         1157|               0|
|          1947|Uniao_Estavel|    74485.0|       0|         1734|               0|
|          1947|Uniao_Estavel|    70321.0|       0|         1376|               0|
|          1947|    Casado(a)|    27469.0|       0|           17|               0|
|          1948|    Casado(a)|    77142.0|       0|          990|               0|
|          1948|    Casado(a)|    92344.0|       0|         1899|               0|
|          1948|  Solteira(o)|    90842.0|       0|         1424|               0|
|          1948|Uniao_Estavel|    51315.0|       0|          222|               0|
|          1948|    Casado(a)|    42192.0|       0|          100|               0|
|          1948|Uniao_Estavel|    70666.0|       0|         1076|               0|
+--------------+-------------+-----------+--------+-------------+----------------+
only showing top 20 rows

In [ ]:
# QUANTOS SOLTEIROS COM DOUTORADO EXISTEM?
solteiros_doutores = df3.select(F.col("estado_civil"), F.col("escolaridade"), F.col("idade")).where((F.col("escolaridade") == "Doutorado") & (F.col("estado_civil") == "Solteira(o)"))

solteiros_doutores.count()

# SÃO 96 PESSOAS SOLTEIRAS COM DOUTORADO

96

In [ ]:
# QUANTAS PESSOAS ACESSARAM O SITE E DO TOTAL DE VENDAS REALIZADAS, QUANTAS DELAS FORAM FEITAS ONLINE?
df3.groupBy(F.col("estado_civil")).sum("Total_compras", "compras_pela_internet").show()
df3.select(F.col("identificacao"), F.col("escolaridade"), F.col("estado_civil"), F.col("n_Filhos")).where(F.col("compras_pela_internet") >= 1).show()

+-------------+------------------+--------------------------+
| estado_civil|sum(Total_compras)|sum(compras_pela_internet)|
+-------------+------------------+--------------------------+
|  Solteira(o)|            288531|                      1814|
|    Casado(a)|            506885|                      3501|
|   Sozinho(a)|               770|                        15|
|Uniao_Estavel|            348869|                      2351|
|    Assexuada|              2385|                         7|
|Divorciada(o)|            141666|                      1000|
|     viuvo(a)|             55325|                       351|
|        Livre|               848|                        14|
+-------------+------------------+--------------------------+

+-------------+------------+-------------+--------+
|identificacao|escolaridade| estado_civil|n_Filhos|
+-------------+------------+-------------+--------+
|         5524|    Bacharel|  Solteira(o)|       0|
|         2174|    Bacharel|  Solteira(o)|       2|
|         4141|    Bacharel|Uniao_Estavel|       0|
|         6182|    Bacharel|Uniao_Estavel|       1|
|         5324|   Doutorado|    Casado(a)|       1|
|         7446|    Mestrado|Uniao_Estavel|       1|
|          965|    Bacharel|Divorciada(o)|       1|
|         6177|   Doutorado|    Casado(a)|       1|
|         4855|   Doutorado|Uniao_Estavel|       1|
|         5899|   Doutorado|Uniao_Estavel|       2|
|          387| Fundamental|    Casado(a)|       0|
|         2125|    Bacharel|Divorciada(o)|       0|
|         8180|    Mestrado|Divorciada(o)|       2|
|         2569|    Bacharel|    Casado(a)|       0|
|         2114|   Doutorado|  Solteira(o)|       0|
|         9736|    Bacharel|    Casado(a)|       2|
|         4939|    Bacharel|Uniao_Estavel|       0|
|         6565|    Mestrado|    Casado(a)|       1|
|         2278|Pos-graduado|  Solteira(o)|       1|
|         9360|    Bacharel|    Casado(a)|       0|
+-------------+------------+-------------+--------+
only showing top 20 rows

JOINS (para criar-los, vou criar grupos de DFs antes)

In [ ]:
join1 = df3.select(F.col("identificacao"), F.col("idade"), F.col("escolaridade"), F.col("Total_vendas"))
join2 = df3.select(F.col("identificacao"), F.col("idade"), F.col("Total_compras"), F.col("Reclamou_de_algo"))

In [ ]:
# VISUALIZAÇÃO DO LADO ESQUERDO
join1.show(10)

+-------------+-----+------------+------------+
|identificacao|idade|escolaridade|Total_vendas|
+-------------+-----+------------+------------+
|         5524|   65|    Bacharel|          22|
|         2174|   68|    Bacharel|           4|
|         4141|   57|    Bacharel|          20|
|         6182|   38|    Bacharel|           6|
|         5324|   41|   Doutorado|          14|
|         7446|   55|    Mestrado|          20|
|          965|   51|    Bacharel|          17|
|         6177|   37|   Doutorado|           8|
|         4855|   48|   Doutorado|           5|
|         5899|   72|   Doutorado|           1|
+-------------+-----+------------+------------+
only showing top 10 rows

In [ ]:
# VISUALIZAÇÃO DO LADO DIREITO
join2.show(10)

+-------------+-----+-------------+----------------+
|identificacao|idade|Total_compras|Reclamou_de_algo|
+-------------+-----+-------------+----------------+
|         5524|   65|         1617|               0|
|         2174|   68|           27|               0|
|         4141|   57|          776|               0|
|         6182|   38|           53|               0|
|         5324|   41|          422|               0|
|         7446|   55|          716|               0|
|          965|   51|          590|               0|
|         6177|   37|          169|               0|
|         4855|   48|           46|               0|
|         5899|   72|           49|               0|
+-------------+-----+-------------+----------------+
only showing top 10 rows

In [ ]:
# FULL OUTER JOIN

df_full = join1.join(join2, on=['identificacao'], how='full')

df_full.show()

+-------------+-----+------------+------------+-----+-------------+----------------+
|identificacao|idade|escolaridade|Total_vendas|idade|Total_compras|Reclamou_de_algo|
+-------------+-----+------------+------------+-----+-------------+----------------+
|            0|   37|    Bacharel|          16|   37|         1198|               0|
|            1|   61|    Bacharel|          17|   61|          577|               0|
|            9|   47|    Mestrado|           7|   47|          120|               0|
|           13|   75|   Doutorado|           4|   75|           32|               0|
|           17|   51|   Doutorado|          24|   51|         1028|               0|
|           20|   57|Pos-graduado|           7|   57|          183|               0|
|           22|   46|    Bacharel|          12|   46|          309|               0|
|           24|   62|    Mestrado|           7|   62|           47|               0|
|           25|   64|    Bacharel|          19|   64|         1115|               0|
|           35|   35|    Bacharel|           7|   35|          210|               0|
|           48|   58|    Bacharel|           8|   58|          184|               0|
|           49|   52|    Bacharel|           4|   52|           25|               0|
|           55|   59|    Bacharel|          18|   59|          597|               0|
|           67|   50|    Mestrado|           6|   50|           92|               0|
|           73|   69|   Doutorado|           3|   69|           18|               0|
|           75|   40|Pos-graduado|          14|   40|          467|               0|
|           78|   53|    Bacharel|           4|   53|           37|               0|
|           87|   41|Pos-graduado|           5|   41|           57|               0|
|           89|   47|Pos-graduado|           6|   47|           69|               0|
|           92|   34|    Bacharel|           7|   34|           89|               0|
+-------------+-----+------------+------------+-----+-------------+----------------+
only showing top 20 rows

## SALVAMENTO E EXPORTAÇÕES

In [ ]:
# ANTES DA EXPORTAÇÃO FINAL, VOU CRIAR UM ULTIMO DATAFRAME DE BACKUP E EXPORTAR COMO CSV.

df_Cunha = df3

df_Cunha.show(10)

+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
|identificacao|ano_nascimento|escolaridade| estado_civil|renda_anual|num_criancas_casa|num_adolescentes_casa|cliente_desde|dias_ultima_compra|Compra_vinho_2anos|Compra_frutas_2anos|Compra_carnes_2anos|Compra_peixes_2anos|Compra_doces_2anos|Compra_ouro_2anos|qtd_descontos_feitos|compras_pela_internet|compras_usando_catalago|compras_feitas_lojaFisica|visitantes_site_mensal|Reclamou_de_algo|idade|n_Filhos|Total_compras|Total_vendas|             media|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
|         5555|          1975|    Bacharel|Divorciada(o)|   153924.0|                0|                    0|   07-02-2014|                81|                 1|                  1|                  1|                  1|                 1|                1|                   0|                    0|                      0|                        0|                     0|               0|   47|       0|            6|           0|              51.0|
|         3955|          1965|    Bacharel|Divorciada(o)|     4861.0|                0|                    0|   22-06-2014|                20|                 2|                  1|                  1|                  1|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   57|       0|            6|           0|              51.0|
|         6862|          1971|    Bacharel|Divorciada(o)|     1730.0|                0|                    0|   18-05-2014|                65|                 1|                  1|                  3|                  1|                 1|                1|                  15|                    0|                      0|                        0|                    20|               0|   51|       0|            8|           0|              51.0|
|        11110|          1973|    Bacharel|  Solteira(o)|     3502.0|                1|                    0|   13-04-2013|                56|                 2|                  1|                  1|                  0|                 0|                1|                   0|                    0|                      0|                        0|                    14|               0|   49|       1|            5|           0|              51.0|
|        10749|          1991|    Bacharel|  Solteira(o)|     8028.0|                0|                    0|   18-09-2012|                62|                73|                 18|                 66|                  7|                12|                2|                  15|                    0|                      1|                        0|                    19|               0|   31|       0|          178|           1|46.833333333333336|
|         9303|          1976|    Bacharel|    Casado(a)|     5305.0|                0|                    1|   30-07-2013|                12|                12|                  4|                  7|                  1|                 3|                5|                   0|                    1|                      0|                        0|                    13|               0|   46|       1|           32|           1|46.833333333333336|
|         8430|          1957|    Bacharel|Uniao_Estavel|    21994.0|                0|                    1|   24-12-2012|                 4|                 9|                  0|                  6|                  3|                 1|                3|                   1|                    0|                      0|                        3|                     5|               0|   65|       1|           22|           3| 49.57142857142857|
|         1386|          1967|    Bacharel|Uniao_Estavel|    32474.0|                1|                    1|   11-05-2014|                 0|                10|                  0|                  1|                  0|                 0|                0|                   1|                    1|                      0|                        2|                     7|               0|   55|       2|           11|           3| 49.57142857142857|
|         5846|          1977|    Bacharel|Divorciada(o)|    40246.0|                1|                    0|   19-12-2012|                68|                 2|                  1|                  6|                  2|                 1|                1|                   1|                    1|                      0|                        2|                     6|               0|   45|       1|           13|           3| 49.57142857142857|
|         2261|          1969|    Bacharel|    Casado(a)|    26304.0|                1|                    0|   23-06-2013|                 5|                 4|                  1|                  5|                  2|                 0|                4|                   1|                    1|                      0|                        2|                     7|               0|   53|       1|           16|           3| 49.57142857142857|
+-------------+--------------+------------+-------------+-----------+-----------------+---------------------+-------------+------------------+------------------+-------------------+-------------------+-------------------+------------------+-----------------+--------------------+---------------------+-----------------------+-------------------------+----------------------+----------------+-----+--------+-------------+------------+------------------+
only showing top 10 rows

In [ ]:
df_final = df_Cunha.toPandas()



---

MONGODB


---

In [ ]:
# EPORTANDO PARA O MONGODB JA TRATADO
# ACESSAR MEU CLUSTER E CRIAR NOVA COLEÇÃO

db = client["aulamongo"]
colecao = db.cunhaTratado

Tirar do comentário caso queira adicinonar o DF novamente no Mongo, pois ja esta adicionado.

In [ ]:
# INSERINDO MANYS 
'''
tratado = df_final.to_dict("records")

colecao.insert_many(tratado)
'''



---
GOOGLE CLOUD STORAGE


---

In [ ]:
# Salvar na Bucket

df_final.to_csv("gs://cunha_tratado_pjindividual/cunha_final.csv", index=False)